
#include <tao/FloatSeq.pidl>

module T4 {

#pragma DCPS_DATA_TYPE "T4::Foo4"
#pragma DCPS_DATA_KEY "T4::Foo4 key"

  typedef sequence<float> FloatSeq;

  // Example user defined "Foo" structure
  struct Foo4 {
    long key;  // the instance key
    FloatSeq values;
  };

};
