
#include <tao/FloatSeq.pidl>

module T4 {

  typedef sequence<float> FloatSeq;

  // Example user defined "Foo" structure
  @topic
  struct Foo4 {
    @key
    long key;  // the instance key
    FloatSeq values;
  };

};
