// The files generated from dds/DCPS/RTPS/TypeLookup.idl will expect
// TypeObjectC.h because it includes TypeObject.idl.  Since TypeObject.idl
// isn't actually processed, we can just make this file and include
// TypeObject.h, which implements what would be generated by TypeObject.idl
// if we had full IDL4 support.

#include "TypeObject.h"
