#ifndef OPENDDS_XTYPES_XML_EXPORT_H
#define OPENDDS_XTYPES_XML_EXPORT_H

#include <ace/config-all.h>

#if defined(ACE_AS_STATIC_LIBS) && !defined(OPENDDS_XTYPES_XML_HAS_DLL)
#  define OPENDDS_XTYPES_XML_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && OPENDDS_XTYPES_XML_HAS_DLL */

#if !defined(OPENDDS_XTYPES_XML_HAS_DLL)
#  define OPENDDS_XTYPES_XML_HAS_DLL 1
#endif /* !OPENDDS_XTYPES_XML_HAS_DLL */

#if defined(OPENDDS_XTYPES_XML_HAS_DLL) && (OPENDDS_XTYPES_XML_HAS_DLL == 1)
#  if defined(OPENDDS_XTYPES_XML_BUILD_DLL)
#    define OpenDDS_XTypes_Xml_Export ACE_Proper_Export_Flag
#    define OPENDDS_XTYPES_XML_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION(T)
#    define OPENDDS_XTYPES_XML_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* OPENDDS_XTYPES_XML_BUILD_DLL */
#    define OpenDDS_XTypes_Xml_Export ACE_Proper_Import_Flag
#    define OPENDDS_XTYPES_XML_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION(T)
#    define OPENDDS_XTYPES_XML_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* OPENDDS_XTYPES_XML_BUILD_DLL */
#else /* OPENDDS_XTYPES_XML_HAS_DLL == 1 */
#  define OpenDDS_XTypes_Xml_Export
#  define OPENDDS_XTYPES_XML_SINGLETON_DECLARATION(T)
#  define OPENDDS_XTYPES_XML_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* OPENDDS_XTYPES_XML_HAS_DLL == 1 */

#if !defined(OPENDDS_XTYPES_XML_NTRACE)
#  if (ACE_NTRACE == 1)
#    define OPENDDS_XTYPES_XML_NTRACE 1
#  else /* ACE_NTRACE == 1 */
#    define OPENDDS_XTYPES_XML_NTRACE 0
#  endif /* ACE_NTRACE == 1 */
#endif /* !OPENDDS_XTYPES_XML_NTRACE */

#if (OPENDDS_XTYPES_XML_NTRACE == 1)
#  define OPENDDS_XTYPES_XML_TRACE(X)
#else /* OPENDDS_XTYPES_XML_NTRACE == 1 */
#  define OPENDDS_XTYPES_XML_TRACE(X) ACE_TRACE_IMPL(X)
#endif /* OPENDDS_XTYPES_XML_NTRACE == 1 */

#endif /* OPENDDS_XTYPES_XML_EXPORT_H */
