#include <tao/orb.idl>

module Xyz {

#pragma DCPS_DATA_TYPE "Xyz::Foo1"
#pragma DCPS_DATA_KEY "Xyz::Foo1 a_long_value"

  // Example user defined "Foo1" structure with a key field and with an
  // unbounded sequence member
  struct Foo1 {
    long  a_long_value;  // the instance key
    long  handle_value;
    long  sample_sequence;
    long  writer_id;
    CORBA::FloatSeq unbounded_sequence;
  };

};
