
module Xyz {

#pragma DCPS_DATA_TYPE "Xyz::Foo2"

  // Example user defined "Foo2" structure without a key field
  struct Foo2 {
    long  a_long_value;
    long  handle_value;
    long  sample_sequence;
    long  writer_id;
  };

};
