#include <tao/orb.idl>

module Xyz {

  // Example user defined "KeyedData" structure with a key field and with an
  // unbounded sequence member
  @topic
  struct KeyedData {
    @key
    long  a_long_value;  // the instance key
    long  handle_value;
    long  sample_sequence;
    long  writer_id;
  };

};
