
module Xyz {

  // Example user defined "NoKeyData" structure without a key field
  @topic
  struct NoKeyData {
    long  a_long_value;
    long  handle_value;
    long  sample_sequence;
    long  writer_id;
  };

};
