enum TestValueAnnotation {
  @value(99) NON_ZERO,
  @value(1) ONE,
  TWO,
  @value(5) FIVE,
  SIX,
  @value(10) TEN
};

struct UsesAnnotatedEnum {
  TestValueAnnotation tva;
};

union DiscByAnnotatedEnum switch (TestValueAnnotation) {
case ONE:
  octet o;
default:
  short s;
};
