module FACE {
  module DM {

    typedef double Latitude, Longitude, Altitude;

    struct Position
    {
      Latitude lat;
      Longitude lon;
      Altitude alt;
    };

    @topic
    struct EGI_Data
    {
      Position pos;
    };


    struct AttitudeBodyFrame
    {
      octet empty;
    };

    @topic
    struct IMU_Data
    {
      AttitudeBodyFrame att;
    };


    @topic
    struct Nav_Data
    {
      Position pos;
      AttitudeBodyFrame att;
    };

  };
};
