
#include "dds/DdsDcpsInfrastructure.idl"
#include "dds/DdsDcpsTopic.idl"
#include "dds/DdsDcpsTypeSupportExt.idl"


// Implied IDL for type "Foo"
// Example user defined structure
@topic
struct Foo {
  @key
  long key;  // the instance key
  float x;
  float y;
  octet o77;
};
