// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl -s SimpleUnreliableDgram
// ------------------------------
#ifndef SIMPLEUNRELIABLEDGRAM_EXPORT_H
#define SIMPLEUNRELIABLEDGRAM_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (SIMPLEUNRELIABLEDGRAM_HAS_DLL)
#  define SIMPLEUNRELIABLEDGRAM_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && SIMPLEUNRELIABLEDGRAM_HAS_DLL */

#if !defined (SIMPLEUNRELIABLEDGRAM_HAS_DLL)
#  define SIMPLEUNRELIABLEDGRAM_HAS_DLL 1
#endif /* !SIMPLEUNRELIABLEDGRAM_HAS_DLL */

#if defined (SIMPLEUNRELIABLEDGRAM_HAS_DLL) && (SIMPLEUNRELIABLEDGRAM_HAS_DLL == 1)
#  if defined (SIMPLEUNRELIABLEDGRAM_BUILD_DLL)
#    define SimpleUnreliableDgram_Export ACE_Proper_Export_Flag
#    define SIMPLEUNRELIABLEDGRAM_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define SIMPLEUNRELIABLEDGRAM_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* SIMPLEUNRELIABLEDGRAM_BUILD_DLL */
#    define SimpleUnreliableDgram_Export ACE_Proper_Import_Flag
#    define SIMPLEUNRELIABLEDGRAM_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define SIMPLEUNRELIABLEDGRAM_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* SIMPLEUNRELIABLEDGRAM_BUILD_DLL */
#else /* SIMPLEUNRELIABLEDGRAM_HAS_DLL == 1 */
#  define SimpleUnreliableDgram_Export
#  define SIMPLEUNRELIABLEDGRAM_SINGLETON_DECLARATION(T)
#  define SIMPLEUNRELIABLEDGRAM_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* SIMPLEUNRELIABLEDGRAM_HAS_DLL == 1 */

// Set SIMPLEUNRELIABLEDGRAM_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (SIMPLEUNRELIABLEDGRAM_NTRACE)
#  if (ACE_NTRACE == 1)
#    define SIMPLEUNRELIABLEDGRAM_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define SIMPLEUNRELIABLEDGRAM_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !SIMPLEUNRELIABLEDGRAM_NTRACE */

#if (SIMPLEUNRELIABLEDGRAM_NTRACE == 1)
#  define SIMPLEUNRELIABLEDGRAM_TRACE(X)
#else /* (SIMPLEUNRELIABLEDGRAM_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define SIMPLEUNRELIABLEDGRAM_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (SIMPLEUNRELIABLEDGRAM_NTRACE == 1) */

#endif /* SIMPLEUNRELIABLEDGRAM_EXPORT_H */

// End of auto generated file.
