set ACE_ROOT=f:\GitHub\OpenDDS_AK\ACE_wrappers
set ALLUSERSPROFILE=C:\ProgramData
set APPDATA=C:\Users\adamk\AppData\Roaming
set BIOMERIEUX_DATA=f:\biomerieux\data
set BIOMERIEUX_PROGRAMS=f:\biomerieux\programs
set CIAO_ROOT=unused
set CommandPromptType=Native
set CommonProgramFiles=C:\Program Files (x86)\Common Files
set CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
set CommonProgramW6432=C:\Program Files\Common Files
set COMPUTERNAME=KILAUEA
set ComSpec=C:\WINDOWS\system32\cmd.exe
set configsetroot=C:\WINDOWS\ConfigSetRoot
set DANCE_ROOT=unused
set DDS_ROOT=f:\GitHub\OpenDDS_AK
set DevEnvDir=c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\
set DriverData=C:\Windows\System32\Drivers\DriverData
set ExtensionSdkDir=C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs
set FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
set FPS_BROWSER_USER_PROFILE_STRING=Default
set Framework40Version=v4.0
set FrameworkDir=C:\Windows\Microsoft.NET\Framework\
set FrameworkDir32=C:\Windows\Microsoft.NET\Framework\
set FrameworkVersion=v4.0.30319
set FrameworkVersion32=v4.0.30319
set HOMEDRIVE=C:
set HOMEPATH=\Users\adamk
set HTMLHelpDir=C:\Program Files (x86)\HTML Help Workshop
set INCLUDE=c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\ATLMFC\include;c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt
set JAVA_HOME=f:\biomerieux\java
set LIB=c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x86;c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\lib\x86;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x86;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x86;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86;
set LIBJABRA_TRACE_LEVEL=debug
set LIBPATH=c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x86;c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\lib\x86;c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\lib\x86\store\references;C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.19041.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.19041.0;C:\Windows\Microsoft.NET\Framework\v4.0.30319;
set LOCALAPPDATA=C:\Users\adamk\AppData\Local
set LOGONSERVER=\\KILAUEA
set MPC_ROOT=f:\GitHub\OpenDDS_AK\ACE_wrappers\MPC
set MSBuildLoadMicrosoftTargetsReadOnly=true
set NETFXSDKDir=C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\
set NUMBER_OF_PROCESSORS=16
set OneDrive=C:\Users\adamk\OneDrive
set OneDriveConsumer=C:\Users\adamk\OneDrive
set OS=Windows_NT
set Path=c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86;c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCPackages;c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow;c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin\Roslyn;c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x86;C:\Program Files (x86)\Windows Kits\10\bin\x86;c:\Program Files (x86)\Microsoft Visual Studio\2017\Profeset ssional\\MSBuild\15.0\bin;C:\Windows\Microsoft.NET\Framework\v4.0.30319;c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\;c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\Tools\;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Program Files (x86)\VMware\VMware Player\bin\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\CMake\bin;C:\Program Files\PuTTY\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\WINDOWS\Sset ystem32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Calibre2\;C:\Program Files\Git\cmd;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;F:\GitHub\OpenDDS\lib;;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Users\adamk\AppData\Local\Microsoft\WindowsApps;C:\Users\adamk\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\adamk\AppData\Local\GitHubDesktop\bin;C:\Users\adamk\.dotnet\tools;;C:\Users\adamk\AppData\Local\Microsoft\WindowsApps;c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;f:\GitHub\OpenDDS_AK\ACE_wrappers\bin;f:\GitHub\OpenDDS_AK\bin;f:\GitHub\OpenDDS_AK\Aset CE_wrappers\lib;f:\GitHub\OpenDDS_AK\lib
set PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
set PkgDefApplicationConfigFile=C:\Users\adamk\AppData\Local\Microsoft\VisualStudio\15.0_09450b11\devenv.exe.config
set PROCESSOR_ARCHITECTURE=x86
set PROCESSOR_ARCHITEW6432=AMD64
set PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
set PROCESSOR_LEVEL=6
set PROCESSOR_REVISION=a502
set ProgramData=C:\ProgramData
set ProgramFiles=C:\Program Files (x86)
set ProgramFiles(x86)=C:\Program Files (x86)
set ProgramW6432=C:\Program Files
set PROMPT=$P$G
set PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
set PUBLIC=C:\Users\Public
set RAPIDJSON_ROOT=f:\GitHub\OpenDDS_AK\tools\rapidjson
set SESSIONNAME=Console
set SystemDrive=C:
set SystemRoot=C:\WINDOWS
set TAO_ROOT=f:\GitHub\OpenDDS_AK\ACE_wrappers\TAO
set TEMP=C:\Users\adamk\AppData\Local\Temp
set TMP=C:\Users\adamk\AppData\Local\Temp
set TRACEDESIGNTIME=true
set UCRTVersion=10.0.19041.0
set UniversalCRTSdkDir=C:\Program Files (x86)\Windows Kits\10\
set USERDOMAIN=KILAUEA
set USERDOMAIN_ROAMINGPROFILE=KILAUEA
set USERNAME=adamk
set USERPROFILE=C:\Users\adamk
set VCIDEInstallDir=c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\
set VCINSTALLDIR=c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\
set VCToolsInstallDir=c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\
set VCToolsRedistDir=c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Redist\MSVC\14.16.27012\
set VCToolsVersion=14.16.27023
set VisualStudioDir=C:\Users\adamk\Documents\Visual Studio 2017
set VisualStudioEdition=Microsoft Visual Studio Professional 2017
set VisualStudioVersion=15.0
set VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
set VS150COMNTOOLS=c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\Tools\
set VSAPPIDDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\
set VSAPPIDNAME=devenv.exe
set VSCMD_ARG_app_plat=Desktop
set VSCMD_ARG_HOST_ARCH=x86
set VSCMD_ARG_no_logo=1
set VSCMD_ARG_TGT_ARCH=x86
set VSCMD_VER=15.9.34
set VSINSTALLDIR=c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\
set VSLANG=1033
set VSSKUEDITION=Professional
set windir=C:\WINDOWS
set WindowsLibPath=C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.19041.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.19041.0
set WindowsSdkBinPath=C:\Program Files (x86)\Windows Kits\10\bin\
set WindowsSdkDir=C:\Program Files (x86)\Windows Kits\10\
set WindowsSDKLibVersion=10.0.19041.0\
set WindowsSdkVerBinPath=C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\
set WindowsSDKVersion=10.0.19041.0\
set WindowsSDK_ExecutablePath_x64=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\
set WindowsSDK_ExecutablePath_x86=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\
set WIX=C:\Program Files (x86)\WiX Toolset v3.11\
set ZES_ENABLE_SYSMAN=1
set __DOTNET_ADD_32BIT=1
set __DOTNET_PREFERRED_BITNESS=32
set __VSCMD_PREINIT_PATH=C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Program Files (x86)\VMware\VMware Player\bin\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\CMake\bin;C:\Program Files\PuTTY\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Calibre2\;C:\Program Files\Git\cmd;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;F:\GitHub\OpenDDS\lib;;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Users\adamk\AppData\Local\Microsoft\WindowsApps;C:\Users\adamk\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\adamk\AppData\Local\GitHubDesktop\bin;C:\Users\adamk\.dotnet\tools;;C:\Users\adamk\AppData\Local\Microsoft\WindowsApps
