@echo off
:: Runs "all 3" code generators:
:: 1. idlj, for comparison to the canonical idl-to-java compiler
:: 2. idl2jni, for testing
:: 3. tao_idl, since the files it generates are #included by the
::    idl2jni-generated code
:: Also compiles the Java and C++ code generated by idl2jni and tao_idl

%JAVA_HOME%\bin\idlj -v -fall -pkgPrefix %1 idlj %1.idl
call %JACORB_HOME%\bin\idl -DUSE_LOCAL -i2jpackage %1:jacorb.%1 %1.idl
tao_idl -v -DUSE_LOCAL %1.idl

::..\..\bin\idl2jni -v %1.idl -DUSE_LOCAL
::%JAVA_HOME%\bin\javac -classpath ..\..\lib\i2jrt.jar %1\*.java
::%ACE_ROOT%\bin\mpc.pl -type vc8 -include ..\.. -base idl2jni -value_template TAO_IDLFLAGS=-DUSE_LOCAL
::vcbuild %1.vcproj
