
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl LivelinessKeepAliveTest
// ------------------------------
#ifndef LIVELINESSKEEPALIVETEST_EXPORT_H
#define LIVELINESSKEEPALIVETEST_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (LIVELINESSKEEPALIVETEST_HAS_DLL)
#  define LIVELINESSKEEPALIVETEST_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && LIVELINESSKEEPALIVETEST_HAS_DLL */

#if !defined (LIVELINESSKEEPALIVETEST_HAS_DLL)
#  define LIVELINESSKEEPALIVETEST_HAS_DLL 1
#endif /* ! LIVELINESSKEEPALIVETEST_HAS_DLL */

#if defined (LIVELINESSKEEPALIVETEST_HAS_DLL) && (LIVELINESSKEEPALIVETEST_HAS_DLL == 1)
#  if defined (LIVELINESSKEEPALIVETEST_BUILD_DLL)
#    define LivelinessKeepAliveTest_Export ACE_Proper_Export_Flag
#    define LIVELINESSKEEPALIVETEST_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define LIVELINESSKEEPALIVETEST_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* LIVELINESSKEEPALIVETEST_BUILD_DLL */
#    define LivelinessKeepAliveTest_Export ACE_Proper_Import_Flag
#    define LIVELINESSKEEPALIVETEST_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define LIVELINESSKEEPALIVETEST_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* LIVELINESSKEEPALIVETEST_BUILD_DLL */
#else /* LIVELINESSKEEPALIVETEST_HAS_DLL == 1 */
#  define LivelinessKeepAliveTest_Export
#  define LIVELINESSKEEPALIVETEST_SINGLETON_DECLARATION(T)
#  define LIVELINESSKEEPALIVETEST_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* LIVELINESSKEEPALIVETEST_HAS_DLL == 1 */

// Set LIVELINESSKEEPALIVETEST_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (LIVELINESSKEEPALIVETEST_NTRACE)
#  if (ACE_NTRACE == 1)
#    define LIVELINESSKEEPALIVETEST_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define LIVELINESSKEEPALIVETEST_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !LIVELINESSKEEPALIVETEST_NTRACE */

#if (LIVELINESSKEEPALIVETEST_NTRACE == 1)
#  define LIVELINESSKEEPALIVETEST_TRACE(X)
#else /* (LIVELINESSKEEPALIVETEST_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define LIVELINESSKEEPALIVETEST_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (LIVELINESSKEEPALIVETEST_NTRACE == 1) */

#endif /* LIVELINESSKEEPALIVETEST_EXPORT_H */

// End of auto generated file.
