//
// (c) Copyright 2008, Object Computing, Inc.
// All Rights Reserved.
//

module Satellite
{
  struct Vector
  {
    long long x;
    long long y;
    long long z;
  };

  @topic
  struct Telemetry
  {
    @key
    string satellite;

    long message_number;

    Vector position;
    Vector velocity;
  };

  typedef string ItemCode;
  const ItemCode FUEL      = "Fuel";
  const ItemCode BATTERY   = "Battery";
  const ItemCode SYSTEM    = "System";

  typedef string AlertCode;
  const AlertCode LOW = "Low";
  const AlertCode DEAD = "Dead";
  const AlertCode SYSTEM_SHUTDOWN = "System Shutdown";

  @topic
  struct Alert
  {
    @key
    string satellite;
    @key
    ItemCode  item;
    AlertCode code;
    string    message;
    long      index;
  };
};
