/*
 * $Id$
 */

#include "enum.idl"
#include "struct.idl"

module foo {
  union union_0 switch (enum_0) {
    case a:   long x;
    case b:
    case c:
    case d:   string s;
    case e:
    default:  struct_0 t;
  };

  union union_1 switch (short) {
    case 0:   long x;
  };
};
