#ifndef TAO_DCPS_TYPE_SUPPORT_IDL
#define TAO_DCPS_TYPE_SUPPORT_IDL

#include "dds/DdsDcpsTopic.idl"
#include "dds/DdsDcpsDataWriterRemote.idl"
#include "dds/DdsDcpsDataReaderRemote.idl"


module TAO {
  module DCPS {

    interface TypeSupport : ::DDS::TypeSupport {

    /**
    * create and activate a FooDataWriter.
    * Implemented by FooTypeSupportImpl.
    * Publisher::create_datawriter() will set the topic, listener, qos and
    * other initialization so the implementation of this method
    * is as small and simple as possible.
    */
    DataWriterRemote create_datawriter();

    /**
    * create and activate a FooDataReader.
    * Implemented by FooTypeSupportImpl.
    * Subscriber::create_datareader() will set the topic, listener, qos and
    * other initialization so the implementation of this method
    * is as small and simple as possible.
    */
    DataReaderRemote create_datareader();

    };
  };
};


#endif /* TAO_DCPS_TYPE_SUPPORT_IDL */
