/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

// ================================================================
/**
 *
 * This file is used to generate the code in ULongSeq*.*
 */
// ================================================================


#ifndef OPENDDS_CORBA_ULONG_SEQ_IDL
#define OPENDDS_CORBA_ULONG_SEQ_IDL

#pragma prefix "omg.org"

module CORBA
{
  typedef sequence<unsigned long> ULongSeq;
};

#endif  /* OPENDDS_CORBA_ULONG_SEQ_IDL */
