/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

/**
 *   This file is used to generate the code in ULongLongSeqC.*
 */

#ifndef OPENDDS_CORBA_ULONGLONG_SEQ_IDL
#define OPENDDS_CORBA_ULONGLONG_SEQ_IDL

#pragma prefix "omg.org"

module CORBA
{
  typedef sequence<unsigned long long> ULongLongSeq;
};

#endif /* OPENDDS_CORBA_ULONGLONG_SEQ_IDL */
