// example adapted from the DCPS Specification v1.2, Annex A, Section 3

@topic
struct LocationInfo {
  @key unsigned long flight_id1;
  @key unsigned long flight_id2;
  long x;
  long y;
  long z;
};

enum FlightType {
  visual,
  instrument,
  mixed
};

typedef string<3> Airport;
typedef sequence<Airport> Airports;

@topic
struct PlanInfo {
  @key unsigned long flight_id1;
  @key unsigned long flight_id2;
  string flight_name;
  string tailno;
  FlightType type;
  Airport departure;
  Airport destination;
  Airports alternative_destinations;
};

@topic
struct MoreInfo {
  @key unsigned long flight_id1;
  string more;
};

// testing cross-joins, this has no keys
@topic
struct UnrelatedInfo {
  string misc;
};

@topic
struct Resulting {
  @key unsigned long flight_id1;
  @key unsigned long flight_id2;
  string flight_name;
  long x;
  long y;
  long height;
  string more;
  string misc;
};
