/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

module RtpsRelay {

  @topic
  struct GroupEntry {
    @key string guid;
    @key string group;
    unsigned long expiration_timestamp;
  };

  @topic
  struct RoutingEntry {
    @key string guid;
    string address;
    string horizontal_relay_address;
    unsigned long expiration_timestamp;
  };

};
