#include <dds/DCPS/Marked_Default_Qos.h>
#include <dds/DCPS/Qos_Helper.h>

#include <gtest/gtest.h>

TEST(dds_DCPS_Marked_Default_Qos, comparisons_are_ubsan_safe)
{
  using OpenDDS::DCPS::operator==;

  EXPECT_TRUE(PARTICIPANT_QOS_DEFAULT == PARTICIPANT_QOS_DEFAULT);
  EXPECT_TRUE(TOPIC_QOS_DEFAULT == TOPIC_QOS_DEFAULT);
  EXPECT_TRUE(DATAWRITER_QOS_DEFAULT == DATAWRITER_QOS_DEFAULT);
  EXPECT_TRUE(PUBLISHER_QOS_DEFAULT == PUBLISHER_QOS_DEFAULT);
  EXPECT_TRUE(DATAREADER_QOS_DEFAULT == DATAREADER_QOS_DEFAULT);
  EXPECT_TRUE(SUBSCRIBER_QOS_DEFAULT == SUBSCRIBER_QOS_DEFAULT);
  EXPECT_TRUE(DATAWRITER_QOS_USE_TOPIC_QOS == DATAWRITER_QOS_USE_TOPIC_QOS);
  EXPECT_TRUE(DATAREADER_QOS_USE_TOPIC_QOS == DATAREADER_QOS_USE_TOPIC_QOS);
}
