//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.29 at 03:59:20 PM CDT 
//


package org.opendds.modeling.sdk.codegen;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for gencontrol complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="gencontrol">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="createHfile" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="createCPPfile" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="createIDLfile" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="createMPCfile" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gencontrol")
public class Gencontrol {

    @XmlAttribute
    protected Boolean createHfile;
    @XmlAttribute
    protected Boolean createCPPfile;
    @XmlAttribute
    protected Boolean createIDLfile;
    @XmlAttribute
    protected Boolean createMPCfile;

    /**
     * Gets the value of the createHfile property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCreateHfile() {
        if (createHfile == null) {
            return false;
        } else {
            return createHfile;
        }
    }

    /**
     * Sets the value of the createHfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCreateHfile(Boolean value) {
        this.createHfile = value;
    }

    /**
     * Gets the value of the createCPPfile property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCreateCPPfile() {
        if (createCPPfile == null) {
            return false;
        } else {
            return createCPPfile;
        }
    }

    /**
     * Sets the value of the createCPPfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCreateCPPfile(Boolean value) {
        this.createCPPfile = value;
    }

    /**
     * Gets the value of the createIDLfile property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCreateIDLfile() {
        if (createIDLfile == null) {
            return false;
        } else {
            return createIDLfile;
        }
    }

    /**
     * Sets the value of the createIDLfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCreateIDLfile(Boolean value) {
        this.createIDLfile = value;
    }

    /**
     * Gets the value of the createMPCfile property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCreateMPCfile() {
        if (createMPCfile == null) {
            return false;
        } else {
            return createMPCfile;
        }
    }

    /**
     * Sets the value of the createMPCfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCreateMPCfile(Boolean value) {
        this.createMPCfile = value;
    }

}
