
// -*- C++ -*-
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl ManualAssertLiveliness
// ------------------------------
#ifndef MANUALASSERTLIVELINESS_EXPORT_H
#define MANUALASSERTLIVELINESS_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (MANUALASSERTLIVELINESS_HAS_DLL)
#  define MANUALASSERTLIVELINESS_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && MANUALASSERTLIVELINESS_HAS_DLL */

#if !defined (MANUALASSERTLIVELINESS_HAS_DLL)
#  define MANUALASSERTLIVELINESS_HAS_DLL 1
#endif /* ! MANUALASSERTLIVELINESS_HAS_DLL */

#if defined (MANUALASSERTLIVELINESS_HAS_DLL) && (MANUALASSERTLIVELINESS_HAS_DLL == 1)
#  if defined (MANUALASSERTLIVELINESS_BUILD_DLL)
#    define ManualAssertLiveliness_Export ACE_Proper_Export_Flag
#    define MANUALASSERTLIVELINESS_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define MANUALASSERTLIVELINESS_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* MANUALASSERTLIVELINESS_BUILD_DLL */
#    define ManualAssertLiveliness_Export ACE_Proper_Import_Flag
#    define MANUALASSERTLIVELINESS_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define MANUALASSERTLIVELINESS_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* MANUALASSERTLIVELINESS_BUILD_DLL */
#else /* MANUALASSERTLIVELINESS_HAS_DLL == 1 */
#  define ManualAssertLiveliness_Export
#  define MANUALASSERTLIVELINESS_SINGLETON_DECLARATION(T)
#  define MANUALASSERTLIVELINESS_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* MANUALASSERTLIVELINESS_HAS_DLL == 1 */

// Set MANUALASSERTLIVELINESS_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (MANUALASSERTLIVELINESS_NTRACE)
#  if (ACE_NTRACE == 1)
#    define MANUALASSERTLIVELINESS_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define MANUALASSERTLIVELINESS_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !MANUALASSERTLIVELINESS_NTRACE */

#if (MANUALASSERTLIVELINESS_NTRACE == 1)
#  define MANUALASSERTLIVELINESS_TRACE(X)
#else /* (MANUALASSERTLIVELINESS_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define MANUALASSERTLIVELINESS_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (MANUALASSERTLIVELINESS_NTRACE == 1) */

#endif /* MANUALASSERTLIVELINESS_EXPORT_H */

// End of auto generated file.
