/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

#include "dds/DdsDcpsCore.idl"

module RtpsRelay {

  // GUID prefix bytes - uniquely specify the participant.
  typedef octet GuidPrefix_t[12];

  // Key portion of Entity identifier.
  typedef octet EntityKey_t[3];

  // Uniquely identify each entity within a participant.
  struct EntityId_t {
    @key EntityKey_t entityKey;
    @key octet entityKind;
  };

  // The actual GUID itself.
  struct GUID_t {
    @key GuidPrefix_t guidPrefix;
    @key EntityId_t entityId;
  };

  @topic
  struct WriterEntry {
    @key GUID_t guid;

    string topic_name;
    string type_name;
    DDS::DataWriterQos data_writer_qos;
    DDS::PublisherQos publisher_qos;
  };

  @topic
  struct ReaderEntry {
    @key GUID_t guid;

    string topic_name;
    string type_name;
    DDS::DataReaderQos data_reader_qos;
    DDS::SubscriberQos subscriber_qos;
  };

  @topic
  struct GuidNameAddress {
    @key GUID_t guid;
    @key string name;
    string address;
  };

  typedef sequence<GUID_t> GuidSequence;

  struct RelayHeader {
    GuidSequence to;
  };

  struct Duration_t {
    long sec;
    unsigned long nanosec;
  };

  @topic
  struct ParticipantStatistics {
    @key GUID_t guid;
    unsigned long messages_in;
    unsigned long long bytes_in;
    unsigned long messages_out;
    unsigned long long bytes_out;
    unsigned long max_fan_out;
    unsigned long error_count;
    Duration_t interval;
    //string last_activity_timestamp;
    //last activity timestamp
  };

  @topic
  struct HandlerStatistics {
    @key GUID_t application_participant_guid;
    @key string name;
    Duration_t interval;
    unsigned long messages_in;
    unsigned long long bytes_in;
    unsigned long messages_out;
    unsigned long long bytes_out;
    unsigned long max_fan_out;
    unsigned long max_queue_size;
    Duration_t max_queue_latency;
    unsigned long local_active_participants;
    unsigned long error_count;
    unsigned long governor_count;
  };

  @topic
  struct DomainStatistics {
    @key GUID_t application_participant_guid;
    unsigned long local_participants;
    unsigned long local_writers;
    unsigned long local_readers;
    unsigned long total_writers;
    unsigned long total_readers;
  };

  @topic
  struct ParticipantEntry {
    @key GUID_t guid;
    DDS::UserDataQosPolicy user_data;
  };

};
