module HeaderTest {

#pragma DCPS_DATA_TYPE "HeaderTest::Message"

  typedef string<255> BoundedString;

  struct Message {
    BoundedString text;
    long count;
    long long msg_instance_guid;
  };

};
