// struct TestStruct {
//     int32 id;
//     string msg;
// };

struct Data {
  sequence<int32> testSeq;
  int32 intTest;
  map<int32, int32> intIntMap;
  // map<int32, int32, 4> intIntMapBounded;

  // map<string, TestStruct> stringStructsMap;
  // map<string, TestStruct, 4> stringStructsMapBounded;

  // map<string, TestStructSeq> stringSequenceMap;
  // map<string, TestStructSeq, 2> stringSequenceMapBounded;

  // map<string, TestStructMap> stringMapMap;
  // map<string, TestStructMap, 2> stringMapMapBounded;

  // map<TestIntStringMap, string> mapStringMap;
};