#if defined __TAO_IDL_FEATURES
#  include __TAO_IDL_FEATURES
#  if TAO_IDL_HAS_MAP
    struct TestStruct {
        int32 id;
        string msg;
    };

    enum TEST_ENUM {TEST1, TEST2, TEST3};

    typedef sequence<TestStruct> TestStructSeq;
    typedef map<int32, TestStruct> TestStructMap;
    typedef map<int32, string> TestIntStringMap; //TODO Not compiling

    @topic
    struct Data {
      map<int32, int32> intIntMap;

      map<string, string> stringStringMap;

      map<TEST_ENUM, int32> enumIntMap;
      map<int32, TEST_ENUM> intEnumMap;

      map<string, TestStruct> stringStructsMap;
      // map<TestStruct, string> structStringMap; // Will not compile

      map<string, TestStructSeq> stringSequenceMap;

      map<string, TestStructMap> stringMapMap;

      map<TestIntStringMap, string> mapStringMap;
    };
  #endif
#endif
