
module profilingTest {

#pragma DCPS_DATA_TYPE "profilingTest::testMsg"
#pragma DCPS_DATA_KEY  "profilingTest::testMsg msgID"

  typedef sequence<octet> OctetSeq;
  struct testMsg {
    unsigned long         msgID;
    unsigned long         count;
    OctetSeq       contents;
  };



};
