<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="types"
    nsURI="http://www.opendds.org/modeling/schemas/Types/1.0" nsPrefix="types">
  <eClassifiers xsi:type="ecore:EClass" name="TopicField" abstract="true" eSuperTypes="Core.ecore#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Simple" abstract="true" eSuperTypes="#//TopicField #//KeyField"/>
  <eClassifiers xsi:type="ecore:EClass" name="Collection" abstract="true" eSuperTypes="#//TopicField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstructedTopicType" abstract="true"
      eSuperTypes="#//TopicField"/>
  <eClassifiers xsi:type="ecore:EClass" name="Typedef" eSuperTypes="#//TopicField">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//TopicField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedefRef" eSuperTypes="#//TopicField">
    <eAnnotations source="GenModel">
      <details key="documentation" value="This is an extension to the ptc/2008-07-02 DDS Profile to allow a typedef defined outside of a TopicStruct, Sequence, or Array topic field to be used as the type within the field."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//Typedef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence" eSuperTypes="#//Collection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subtype" lowerBound="1"
        eType="#//TopicField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Array" eSuperTypes="#//Collection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subtype" lowerBound="1"
        eType="#//TopicField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//Collection #//KeyField"/>
  <eClassifiers xsi:type="ecore:EClass" name="Case">
    <eStructuralFeatures xsi:type="ecore:EReference" name="labels" lowerBound="1"
        eType="#//Sequence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element_spec" lowerBound="1"
        eType="#//TopicField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Union" eSuperTypes="#//ConstructedTopicType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="switch" lowerBound="1"
        eType="#//TopicField"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" lowerBound="1" upperBound="-1"
        eType="#//Case"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopicStruct" eSuperTypes="#//ConstructedTopicType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" lowerBound="1"
        upperBound="-1" eType="#//TopicField" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keys" upperBound="-1" eType="#//Key"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//Simple"/>
  <eClassifiers xsi:type="ecore:EClass" name="Char" eSuperTypes="#//Simple"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enum" eSuperTypes="#//Simple">
    <eStructuralFeatures xsi:type="ecore:EReference" name="labels" upperBound="-1"
        eType="#//Sequence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatingPoint" eSuperTypes="#//Simple"/>
  <eClassifiers xsi:type="ecore:EClass" name="Double" eSuperTypes="#//FloatingPoint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Float" eSuperTypes="#//FloatingPoint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Int" abstract="true" eSuperTypes="#//Simple"/>
  <eClassifiers xsi:type="ecore:EClass" name="SignedInt" abstract="true" eSuperTypes="#//Int"/>
  <eClassifiers xsi:type="ecore:EClass" name="Short" eSuperTypes="#//SignedInt"/>
  <eClassifiers xsi:type="ecore:EClass" name="Integer" eSuperTypes="#//SignedInt"/>
  <eClassifiers xsi:type="ecore:EClass" name="Long" eSuperTypes="#//SignedInt"/>
  <eClassifiers xsi:type="ecore:EClass" name="LongLong" eSuperTypes="#//SignedInt"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnsignedInt" abstract="true" eSuperTypes="#//Int"/>
  <eClassifiers xsi:type="ecore:EClass" name="UShort" eSuperTypes="#//UnsignedInt"/>
  <eClassifiers xsi:type="ecore:EClass" name="UInteger" eSuperTypes="#//UnsignedInt"/>
  <eClassifiers xsi:type="ecore:EClass" name="ULong" eSuperTypes="#//UnsignedInt"/>
  <eClassifiers xsi:type="ecore:EClass" name="ULongLong" eSuperTypes="#//UnsignedInt"/>
  <eClassifiers xsi:type="ecore:EClass" name="Octet" eSuperTypes="#//Simple"/>
  <eClassifiers xsi:type="ecore:EClass" name="KeyField" abstract="true">
    <eAnnotations source="GenModel">
      <details key="documentation" value="A base class for any topic field that can be a Key in a TopicStruct. This is an extension to UML Profile for Data Distribution Specification (ptc/2008-07-02)."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Key">
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" lowerBound="1"
        eType="#//KeyField"/>
  </eClassifiers>
</ecore:EPackage>
