module HelloWorld {

  const long HELLO_WORLD_DOMAIN = 1;

  enum State { Initial, /*Intermediate,*/ Complete };

  @topic
  struct Message {
    string value;
    State current;
  };

  const string MESSAGE_TOPIC1_NAME = "OldToNew";
  const string MESSAGE_TOPIC2_NAME = "NewToOld";

  const string OLDAPP = "OLD";
  const string NEWAPP = "NEW";
  const string NEWAPP_READY = "NEWAPP_READY";
  const string OLDAPP_DONE = "OLDAPP_DONE";
};
