// TODO(iguessthislldo): Add more fields
#define COMMON_FIELDS \
  short short_field; \
  long long_field; \
  octet octet_field; \
  long long long_long_field; \

// Generic XCDR1 Tests =======================================================

@final
@OpenDDS::data_representation(XCDR1)
struct FinalXcdr1Struct {
  COMMON_FIELDS
};

@appendable
@OpenDDS::data_representation(XCDR1)
struct AppendableXcdr1Struct {
  COMMON_FIELDS
};

@mutable
@OpenDDS::data_representation(XCDR1)
struct MutableXcdr1Struct {
  COMMON_FIELDS
};

// Generic XCDR2 Tests =======================================================

@final
@OpenDDS::data_representation(XCDR2)
struct FinalXcdr2Struct {
  COMMON_FIELDS
};

@appendable
@OpenDDS::data_representation(XCDR2)
struct AppendableXcdr2Struct {
  COMMON_FIELDS
};

@mutable
@OpenDDS::data_representation(XCDR2)
struct MutableXcdr2Struct {
  COMMON_FIELDS
};

// Generic XCDR1/2 Tests =====================================================

@final
@OpenDDS::data_representation(XCDR1)
@OpenDDS::data_representation(XCDR2)
struct FinalXcdr12Struct {
  COMMON_FIELDS
};

@appendable
@OpenDDS::data_representation(XCDR1)
@OpenDDS::data_representation(XCDR2)
struct AppendableXcdr12Struct {
  COMMON_FIELDS
};

@mutable
@OpenDDS::data_representation(XCDR1)
@OpenDDS::data_representation(XCDR2)
struct MutableXcdr12Struct {
  COMMON_FIELDS
};

enum CommonFields {
  E_SHORT_FIELD,
  E_LONG_FIELD,
  E_OCTET_FIELD,
  E_LONG_LONG_FIELD
};

@mutable
@OpenDDS::data_representation(XCDR1)
@OpenDDS::data_representation(XCDR2)
union MutableXcdr12Union switch (CommonFields) {
case E_SHORT_FIELD:
  short short_field;
case E_LONG_FIELD:
  long long_field;
case E_OCTET_FIELD:
  octet octet_field;
case E_LONG_LONG_FIELD:
  long long long_long_field;
};

// Appendable Tests ==========================================================
// TODO(iguessthislldo)

// Mutable Tests =============================================================
// TODO(iguessthislldo): Add more fields

@mutable
@OpenDDS::data_representation(XCDR1)
@OpenDDS::data_representation(XCDR2)
struct MutableStruct {
  @id(4) short short_field;
  @id(6) long long_field;
  @id(8) octet octet_field;
  @id(10) long long long_long_field;
};

@mutable
@OpenDDS::data_representation(XCDR1)
@OpenDDS::data_representation(XCDR2)
struct ReorderedMutableStruct {
  @id(6) long long_field;
  @id(10) long long long_long_field;
  @id(8) octet octet_field;
  @id(4) short short_field;
};

@mutable
@OpenDDS::data_representation(XCDR1)
@OpenDDS::data_representation(XCDR2)
struct AdditionalFieldMutableStruct {
  @id(6) long long_field;
  @id(1) long additional_field;
  @id(10) long long long_long_field;
  @id(8) octet octet_field;
  @id(4) short short_field;
};

@mutable
@OpenDDS::data_representation(XCDR1)
@OpenDDS::data_representation(XCDR2)
union MutableUnion switch (CommonFields) {
case E_SHORT_FIELD:
  @id(4) short short_field;
case E_LONG_FIELD:
  @id(6) long long_field;
case E_OCTET_FIELD:
  @id(8) octet octet_field;
case E_LONG_LONG_FIELD:
  @id(10) long long long_long_field;
};
