// note the following predefined types often have special cases:
//    char, octet, boolean, string
// where as all of the integer and float types are just one case.

#include "SharedTypes.idl"

module Xyz {

  // needed to detect duplicate overload problems
  typedef sequence<boolean,3> SeqOfBoolean2;
  typedef sequence<string,3>  SeqOfString2;
  typedef sequence<char,3>    SeqOfChar2;
  typedef sequence<octet,3>   SeqOfOctet2;
  typedef sequence<long,3>    SeqOfLong2;
  typedef sequence<AnEnum,3>  SeqOfAnEnum2;

  struct SimpleStruct {
    long simple;
    SeqOfLong ss1;
  };

  // needed to call size methods on arrays
#ifdef USE_TOPIC_ANNOTATIONS
  @topic
#else
#  pragma DCPS_DATA_TYPE "Xyz::StructOfArrayOfSeqOfBoolean"
#endif
  struct StructOfArrayOfSeqOfBoolean { ArrayOfSeqOfBoolean f; };

#ifdef USE_TOPIC_ANNOTATIONS
  @topic
#else
#  pragma DCPS_DATA_TYPE "Xyz::StructOfArrayOfSeqOfString"
#endif
  struct StructOfArrayOfSeqOfString { ArrayOfSeqOfString f;};

#ifdef USE_TOPIC_ANNOTATIONS
  @topic
#else
#  pragma DCPS_DATA_TYPE "Xyz::StructOfArrayOfSeqOfChar"
#endif
  struct StructOfArrayOfSeqOfChar { ArrayOfSeqOfChar f;};

#ifdef USE_TOPIC_ANNOTATIONS
  @topic
#else
#  pragma DCPS_DATA_TYPE "Xyz::StructOfArrayOfSeqOfOctet"
#endif
  struct StructOfArrayOfSeqOfOctet { ArrayOfSeqOfOctet f;};

#ifdef USE_TOPIC_ANNOTATIONS
  @topic
#else
#  pragma DCPS_DATA_TYPE "Xyz::StructOfArrayOfSeqOfLong"
#endif
  struct StructOfArrayOfSeqOfLong { ArrayOfSeqOfLong f;};

#ifdef USE_TOPIC_ANNOTATIONS
  @topic
#else
#  pragma DCPS_DATA_TYPE "Xyz::StructOfArrayOfSeqOfAnEnum"
#endif
  struct StructOfArrayOfSeqOfAnEnum { ArrayOfSeqOfAnEnum f;};
};
