/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

module OptionalTest {

  const long OPTIONAL_DOMAIN = 111;

  @topic
  struct Message {
    @optional string value;
  };

  const string MESSAGE_TOPIC_NAME = "OptionalTest";

  const string PUBLISHER = "PUBLISHER";
  const string SUBSCRIBER = "SUBSCRIBER";
  const string SUBSCRIBER_READY = "SUBSCRIBER_READY";
  const string SUBSCRIBER_DONE = "SUBSCRIBER_DONE";
};
