# This file is partially generated by matrix.py

# Android Target, Required
export ndk=r28c
export arch=arm64
export api=24

# Optional Settings

# Java, defaults to false
#export use_java=true

# Target API, required for Java on Android
#export target_api=30

# JDK location, defaults to "", no argument to --java (Try to use system default)
#export jdk=

# Security, defaults to false
#export use_security=true

# Build $ACE_ROOT/tests, defaults to true
#export build_ace_tests=false

# Prebuilt Host Tools Root, defaults to blank (Build Tools)
#export host_tools=

# What ACE/TAO to use, defaults to doc_group_master
#export ace_tao=doc_group_ace6_tao2 # DOC Group ACE 6/TAO 2

# Build using a standalone toolchain, defaults to using the NDK directly.
#export use_toolchain=true

# Enable concurrent MPC in OpenDDS's configure script (defaults to true)
#export mpc_concurrent=false
