//
// $Id$
//

/// Put the interfaces in a module, to avoid global namespace pollution
module Test
{
  
  interface TestPubDriver
  {
    /// A method to shutdown the PubDriver
    /**
     * This method is used to simplify the test shutdown process
     */
    oneway void shutdown ();
  };
};
