<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Diagrams"
    nsURI="http://www.opendds.org/modeling/schemas/Diagrams/1.0" nsPrefix="diagrams">
  <eClassifiers xsi:type="ecore:EClass" name="DcpsDomains">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" upperBound="-1"
        eType="ecore:EClass OpenDDS.ecore#//domain" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participant" upperBound="-1"
        eType="ecore:EClass OpenDDS.ecore#//domainParticipant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topic" upperBound="-1"
        eType="ecore:EClass OpenDDS.ecore#//topic" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PolicyLibrary">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="policy" upperBound="-1"
        eType="ecore:EClass OpenDDS.ecore#//qosPolicy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypes"/>
</ecore:EPackage>
