/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

#ifndef OPENDDS_DCPS_CONDITIONSEQ_IDL
#define OPENDDS_DCPS_CONDITIONSEQ_IDL

module DDS {
    local interface Condition;
    typedef sequence<Condition> ConditionSeq;
};

#endif  /* OPENDDS_DCPS_CONDITIONSEQ_IDL */
