/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

#ifndef OPENDDS_DDSDCPS_IDL
#define OPENDDS_DDSDCPS_IDL

#include <dds/DdsDcpsDomain.idl>

#endif /* OPENDDS_DCPS_IDL */
