/*
 * $Id$
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

#ifndef OPENDDS_DCPS_CORE_IDL
#define OPENDDS_DCPS_CORE_IDL

module DDS {

};

#endif  /* OPENDDS_DCPS_CORE_IDL */
