/*
 * $Id$
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

#ifndef OPENDDS_DCPSINFO_IDL
#define OPENDDS_DCPSINFO_IDL

#include "dds/DdsDcpsInfoUtils.idl"

module OpenDDS {
  module DCPS {

    // Information returned from call to add_domain_participant()
    struct AddDomainStatus {
      RepoId  id;
      boolean federated;
    };

    // Status returned by a topic operation
    enum TopicStatus {
      CREATED,
      ENABLED,
      FOUND,
      NOT_FOUND,
      REMOVED,
      CONFLICTING_TYPENAME,
      INTERNAL_ERROR
    };

  }; // module DDS
}; // module OpenDDS

#endif /* OPENDDS_DCPSINFO_IDL */
