/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 *
 * This file contains common functionality shared between RtpsCore.idl and
 * DdsSecurityCore.idl. In particular, dependencies for the Parameter types
 * added by the DDS Security Spec.
 *
 */

#ifdef OPENDDS_SECURITY
#ifndef OPENDDS_DDS_SECURITY_PARAMS_IDL
#define OPENDDS_DDS_SECURITY_PARAMS_IDL

#include "DdsDcpsCore.idl"

module DDS {
  module Security {

    typedef unsigned short ParameterId_t;

    // Security-specific parameters
    // The DDS Security specification reserves ParameterIDs in the range: 0x1000 to
    // 0x1FFF and 0x5000 to 0x5FFF.
    const ParameterId_t PID_IDENTITY_TOKEN = 0x1001;
    const ParameterId_t PID_PERMISSIONS_TOKEN = 0x1002;
    const ParameterId_t PID_DATA_TAGS = 0x1003;
    const ParameterId_t PID_ENDPOINT_SECURITY_INFO = 0x1004;
    const ParameterId_t PID_PARTICIPANT_SECURITY_INFO = 0x1005;
    const ParameterId_t PID_IDENTITY_STATUS_TOKEN = 0x1006;
    // https://issues.omg.org/browse/DDSSEC12-87
    const ParameterId_t PID_EXTENDED_BUILTIN_ENDPOINTS = 0x1007;

    struct DataHolder {
      string             class_id;
      PropertySeq        properties;
      BinaryPropertySeq  binary_properties;
    };
    typedef sequence<DataHolder> DataHolderSeq;

    typedef DataHolder Token;
    typedef Token IdentityToken;
    typedef Token PermissionsToken;
    typedef Token IdentityStatusToken;

    struct Tag {
      string name;
      string value;
    };

    typedef sequence<Tag> TagSeq;
    struct DataTags {
      TagSeq tags;
    };

    typedef unsigned long ParticipantSecurityAttributesMask;

    const ParticipantSecurityAttributesMask PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_IS_RTPS_PROTECTED = 1 << 0;
    const ParticipantSecurityAttributesMask PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_IS_DISCOVERY_PROTECTED = 1 << 1;
    const ParticipantSecurityAttributesMask PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_IS_LIVELINESS_PROTECTED = 1 << 2;
    const ParticipantSecurityAttributesMask PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_IS_VALID = 1 << 31;

    typedef unsigned long PluginParticipantSecurityAttributesMask;

    const ParticipantSecurityAttributesMask PLUGIN_PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_IS_RTPS_ENCRYPTED = 1 << 0;
    const ParticipantSecurityAttributesMask PLUGIN_PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_BUILTIN_IS_DISCOVERY_ENCRYPTED = 1 << 1;
    const ParticipantSecurityAttributesMask PLUGIN_PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_IS_LIVELINESS_ENCRYPTED = 1 << 2;
    const ParticipantSecurityAttributesMask PLUGIN_PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_IS_RTPS_ORIGIN_AUTHENTICATED = 1 << 3;
    const ParticipantSecurityAttributesMask PLUGIN_PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_IS_DISCOVERY_ORIGIN_AUTHENTICATED = 1 << 4;
    const ParticipantSecurityAttributesMask PLUGIN_PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_IS_LIVELINESS_ORIGIN_AUTHENTICATED = 1 << 5;
    const ParticipantSecurityAttributesMask PLUGIN_PARTICIPANT_SECURITY_ATTRIBUTES_FLAG_IS_VALID = 1 << 31;

    //@extensibility(APPENDABLE)
    struct ParticipantSecurityInfo {
      ParticipantSecurityAttributesMask        participant_security_attributes;
      PluginParticipantSecurityAttributesMask  plugin_participant_security_attributes;
    };

    typedef unsigned long EndpointSecurityAttributesMask;
    typedef unsigned long PluginEndpointSecurityAttributesMask;

    const EndpointSecurityAttributesMask ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_READ_PROTECTED = 1 << 0;
    const EndpointSecurityAttributesMask ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_WRITE_PROTECTED = 1 << 1;
    const EndpointSecurityAttributesMask ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_DISCOVERY_PROTECTED = 1 << 2;
    const EndpointSecurityAttributesMask ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_SUBMESSAGE_PROTECTED = 1 << 3;
    const EndpointSecurityAttributesMask ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_PAYLOAD_PROTECTED = 1 << 4;
    const EndpointSecurityAttributesMask ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_KEY_PROTECTED = 1 << 5;
    const EndpointSecurityAttributesMask ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_LIVELINESS_PROTECTED = 1 << 6;
    const EndpointSecurityAttributesMask ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_VALID = 1 << 31;

    const PluginEndpointSecurityAttributesMask PLUGIN_ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_SUBMESSAGE_ENCRYPTED = 1 << 0;
    const PluginEndpointSecurityAttributesMask PLUGIN_ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_PAYLOAD_ENCRYPTED = 1 << 1;
    const PluginEndpointSecurityAttributesMask PLUGIN_ENDPOINT_SECURITY_ATTRIBUTES_FLAG_IS_SUBMESSAGE_ORIGIN_AUTHENTICATED = 1 << 2;

    //@extensibility(APPENDABLE)
    struct EndpointSecurityInfo {
      EndpointSecurityAttributesMask        endpoint_security_attributes;
      PluginEndpointSecurityAttributesMask  plugin_endpoint_security_attributes;
    };

    typedef unsigned long BuiltinEndpointSet_t;
    const BuiltinEndpointSet_t SEDP_BUILTIN_PUBLICATIONS_SECURE_WRITER = 1 << 16;
    const BuiltinEndpointSet_t SEDP_BUILTIN_PUBLICATIONS_SECURE_READER = 1 << 17;
    const BuiltinEndpointSet_t SEDP_BUILTIN_SUBSCRIPTIONS_SECURE_WRITER = 1 << 18;
    const BuiltinEndpointSet_t SEDP_BUILTIN_SUBSCRIPTIONS_SECURE_READER = 1 << 19;
    const BuiltinEndpointSet_t BUILTIN_PARTICIPANT_MESSAGE_SECURE_WRITER = 1 << 20;
    const BuiltinEndpointSet_t BUILTIN_PARTICIPANT_MESSAGE_SECURE_READER = 1 << 21;
    const BuiltinEndpointSet_t BUILTIN_PARTICIPANT_STATELESS_MESSAGE_WRITER = 1 << 22;
    const BuiltinEndpointSet_t BUILTIN_PARTICIPANT_STATELESS_MESSAGE_READER = 1 << 23;
    const BuiltinEndpointSet_t BUILTIN_PARTICIPANT_VOLATILE_MESSAGE_SECURE_WRITER = 1 << 24;
    const BuiltinEndpointSet_t BUILTIN_PARTICIPANT_VOLATILE_MESSAGE_SECURE_READER = 1 << 25;
    const BuiltinEndpointSet_t SPDP_BUILTIN_PARTICIPANT_SECURE_WRITER = 1 << 26;
    const BuiltinEndpointSet_t SPDP_BUILTIN_PARTICIPANT_SECURE_READER = 1 << 27;

    // https://issues.omg.org/browse/DDSSEC12-87
    typedef unsigned long ExtendedBuiltinEndpointSet_t;
    const ExtendedBuiltinEndpointSet_t TYPE_LOOKUP_SERVICE_REQUEST_WRITER_SECURE = 1 << 0;
    const ExtendedBuiltinEndpointSet_t TYPE_LOOKUP_SERVICE_REQUEST_READER_SECURE = 1 << 1;
    const ExtendedBuiltinEndpointSet_t TYPE_LOOKUP_SERVICE_REPLY_WRITER_SECURE = 1 << 2;
    const ExtendedBuiltinEndpointSet_t TYPE_LOOKUP_SERVICE_REPLY_READER_SECURE = 1 << 3;
  };
};

#endif /* DDS_SECURITY_PARAMS_IDL */
#endif
