/*
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

#ifndef OPENDDS_CONFIG_WRAPPER_H
#define OPENDDS_CONFIG_WRAPPER_H

// OpenDDSConfig.h is generated by the configure script or by CMake
// If you're manually configuring OpenDDS, start by creating an empty file
// named OpenDDSConfig.h in a dds/ directory on the include path.
// See the OpenDDS Developer's Guide and dds/OpenDDSConfig.h.in for details
// regarding what can be customized.
#include <dds/OpenDDSConfig.h>

#if defined DDS_HAS_MINIMUM_BIT && defined OPENDDS_CONFIG_BUILT_IN_TOPICS
#  if OPENDDS_CONFIG_BUILT_IN_TOPICS
#    error DDS_HAS_MINIMUM_BIT is defined but OPENDDS_CONFIG_BUILT_IN_TOPICS=1
#  endif
#elif defined DDS_HAS_MINIMUM_BIT
#  define OPENDDS_CONFIG_BUILT_IN_TOPICS 0
#elif defined OPENDDS_CONFIG_BUILT_IN_TOPICS
#  if !OPENDDS_CONFIG_BUILT_IN_TOPICS
#    define DDS_HAS_MINIMUM_BIT
#  endif
#else
#  define OPENDDS_CONFIG_BUILT_IN_TOPICS 1
#endif

#if defined OPENDDS_NO_CONTENT_FILTERED_TOPIC && defined OPENDDS_CONFIG_CONTENT_FILTERED_TOPIC
#  if OPENDDS_CONFIG_CONTENT_FILTERED_TOPIC
#    error OPENDDS_NO_CONTENT_FILTERED_TOPIC is defined but OPENDDS_CONFIG_CONTENT_FILTERED_TOPIC=1
#  endif
#elif defined OPENDDS_NO_CONTENT_FILTERED_TOPIC
#  define OPENDDS_CONFIG_CONTENT_FILTERED_TOPIC 0
#elif defined OPENDDS_CONFIG_CONTENT_FILTERED_TOPIC
#  if !OPENDDS_CONFIG_CONTENT_FILTERED_TOPIC
#    define OPENDDS_NO_CONTENT_FILTERED_TOPIC
#  endif
#else
#  define OPENDDS_CONFIG_CONTENT_FILTERED_TOPIC 1
#endif

#if defined OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE && defined OPENDDS_CONFIG_CONTENT_SUBSCRIPTION
#  if OPENDDS_CONFIG_CONTENT_SUBSCRIPTION
#    error OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE is defined but OPENDDS_CONFIG_CONTENT_SUBSCRIPTION=1
#  endif
#elif defined OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
#  define OPENDDS_CONFIG_CONTENT_SUBSCRIPTION 0
#elif defined OPENDDS_CONFIG_CONTENT_SUBSCRIPTION
#  if !OPENDDS_CONFIG_CONTENT_SUBSCRIPTION
#    define OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
#  endif
#else
#  define OPENDDS_CONFIG_CONTENT_SUBSCRIPTION 1
#endif

#if defined OPENDDS_SECURITY && defined OPENDDS_CONFIG_SECURITY
#  if !OPENDDS_CONFIG_SECURITY
#    error OPENDDS_SECURITY is defined but OPENDDS_CONFIG_SECURITY=0
#  endif
#elif defined OPENDDS_SECURITY
#  define OPENDDS_CONFIG_SECURITY 1
#elif defined OPENDDS_CONFIG_SECURITY
#  if OPENDDS_CONFIG_SECURITY
#    define OPENDDS_SECURITY
#  endif
#else
#  define OPENDDS_CONFIG_SECURITY 0
#endif

#if defined OPENDDS_NO_QUERY_CONDITION && defined OPENDDS_CONFIG_QUERY_CONDITION
#  if OPENDDS_CONFIG_QUERY_CONDITION
#    error OPENDDS_NO_QUERY_CONDITION is defined but OPENDDS_CONFIG_QUERY_CONDITION=1
#  endif
#elif defined OPENDDS_NO_QUERY_CONDITION
#  define OPENDDS_CONFIG_QUERY_CONDITION 0
#elif defined OPENDDS_CONFIG_QUERY_CONDITION
#  if !OPENDDS_CONFIG_QUERY_CONDITION
#    define OPENDDS_NO_QUERY_CONDITION
#  endif
#else
#  define OPENDDS_CONFIG_QUERY_CONDITION 1
#endif

// If features content_filtered_topic, multi_topic, and query_condition
// are all disabled, define a macro to indicate common code these
// three features depend on should not be built.
#if !OPENDDS_CONFIG_QUERY_CONDITION && !OPENDDS_CONFIG_CONTENT_FILTERED_TOPIC && defined OPENDDS_NO_MULTI_TOPIC
#  define OPENDDS_CONFIG_CONTENT_SUBSCRIPTION 0
#endif

#endif
