/*
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

#ifndef OPENDDS_CONFIG_WRAPPER_H
#define OPENDDS_CONFIG_WRAPPER_H

// OpenDDSConfig.h is generated by the configure script or by CMake
// If you're manually configuring OpenDDS, start by creating an empty file
// named OpenDDSConfig.h in a dds/ directory on the include path.
// See the OpenDDS Developer's Guide and dds/OpenDDSConfig.h.in for details
// regarding what can be customized.
#include <dds/OpenDDSConfig.h>

#if defined OPENDDS_SECURITY && defined OPENDDS_CONFIG_SECURITY
#  if !OPENDDS_CONFIG_SECURITY
#    error OPENDDS_SECURITY is defined but OPENDDS_CONFIG_SECURITY=0
#  endif
#elif defined OPENDDS_SECURITY
#  define OPENDDS_CONFIG_SECURITY 1
#elif defined OPENDDS_CONFIG_SECURITY
#  if OPENDDS_CONFIG_SECURITY
#    define OPENDDS_SECURITY
#  endif
#else
#  define OPENDDS_CONFIG_SECURITY 0
#endif

#endif
