/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

#ifndef OPENDDS_VERSION_H
#define OPENDDS_VERSION_H

#define OPENDDS_MAJOR_VERSION 4
#define OPENDDS_MINOR_VERSION 0
#define OPENDDS_MICRO_VERSION 0
#define OPENDDS_VERSION_METADATA "dev"
#define OPENDDS_IS_RELEASE 0
#define OPENDDS_VERSION "4.0.0-dev"

#define OPENDDS_VERSION_AT_LEAST(MAJOR, MINOR, MICRO) (\
  (OPENDDS_MAJOR_VERSION > (MAJOR)) || \
  (OPENDDS_MAJOR_VERSION == (MAJOR) && OPENDDS_MINOR_VERSION >= (MINOR)) || \
  (OPENDDS_MAJOR_VERSION == (MAJOR) && OPENDDS_MINOR_VERSION == (MINOR) && \
    (OPENDDS_MICRO_VERSION >= (MICRO)) \
  ) \
)

#define OPENDDS_VERSION_EXACTLY(MAJOR, MINOR, MICRO) (OPENDDS_MAJOR_VERSION == (MAJOR) && \
  OPENDDS_MINOR_VERSION == (MINOR) && OPENDDS_MICRO_VERSION == (MICRO))

#define OPENDDS_VERSION_LESS_THAN(MAJOR, MINOR, MICRO) \
  !OPENDDS_VERSION_AT_LEAST((MAJOR), (MINOR), (MICRO))

#endif // OPENDDS_VERSION_H
