#if ! defined PTDEF_IDL
#define PTDEF_IDL

module Xyz {

// No key in struct.

  typedef sequence<float, 128> Flt128Seq;
  @topic
  struct Pt128 {
    long data_source;
    long sequence_num;
    Flt128Seq values;
  };

  typedef sequence<float, 512> Flt512Seq;
  @topic
  struct Pt512 {
    long data_source;
    long sequence_num;
    Flt512Seq values;
  };

  typedef sequence<float, 2048> Flt2048Seq;
  @topic
  struct Pt2048 {
    long data_source;
    long sequence_num;
    Flt2048Seq values;
  };

  typedef sequence<float, 8192> Flt8192Seq;
  @topic
  struct Pt8192 {
    long data_source;
    long sequence_num;
    Flt8192Seq values;
  };
};

#endif /* PTDEF_IDL */
