
// -*- C++ -*-
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl BuiltInTopicTest
// ------------------------------
#ifndef BUILTINTOPICTEST_EXPORT_H
#define BUILTINTOPICTEST_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (BUILTINTOPICTEST_HAS_DLL)
#  define BUILTINTOPICTEST_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && BUILTINTOPICTEST_HAS_DLL */

#if !defined (BUILTINTOPICTEST_HAS_DLL)
#  define BUILTINTOPICTEST_HAS_DLL 1
#endif /* ! BUILTINTOPICTEST_HAS_DLL */

#if defined (BUILTINTOPICTEST_HAS_DLL) && (BUILTINTOPICTEST_HAS_DLL == 1)
#  if defined (BUILTINTOPICTEST_BUILD_DLL)
#    define BuiltInTopicTest_Export ACE_Proper_Export_Flag
#    define BUILTINTOPICTEST_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define BUILTINTOPICTEST_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* BUILTINTOPICTEST_BUILD_DLL */
#    define BuiltInTopicTest_Export ACE_Proper_Import_Flag
#    define BUILTINTOPICTEST_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define BUILTINTOPICTEST_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* BUILTINTOPICTEST_BUILD_DLL */
#else /* BUILTINTOPICTEST_HAS_DLL == 1 */
#  define BuiltInTopicTest_Export
#  define BUILTINTOPICTEST_SINGLETON_DECLARATION(T)
#  define BUILTINTOPICTEST_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* BUILTINTOPICTEST_HAS_DLL == 1 */

// Set BUILTINTOPICTEST_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (BUILTINTOPICTEST_NTRACE)
#  if (ACE_NTRACE == 1)
#    define BUILTINTOPICTEST_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define BUILTINTOPICTEST_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !BUILTINTOPICTEST_NTRACE */

#if (BUILTINTOPICTEST_NTRACE == 1)
#  define BUILTINTOPICTEST_TRACE(X)
#else /* (BUILTINTOPICTEST_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define BUILTINTOPICTEST_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (BUILTINTOPICTEST_NTRACE == 1) */

#endif /* BUILTINTOPICTEST_EXPORT_H */

// End of auto generated file.
