// *******************************************************************
//
// (c) Copyright 2006, Object Computing, Inc.
// All Rights Reserved.
//
// *******************************************************************

module StockQuoter {

  typedef unsigned long long TimeT;

  @topic
  struct Quote {
    @key string ticker;
    string exchange;
    string full_name;
    double value;
    TimeT timestamp;
  };

  enum ExchangeEventType { TRADING_OPENED,
                           TRADING_CLOSED,
                           TRADING_SUSPENDED,
                           TRADING_RESUMED };
  @topic
  struct ExchangeEvent {
    @key string exchange;
    ExchangeEventType event;
    TimeT timestamp;
  };
};
