
// -*- C++ -*-
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl TransientDurability
// ------------------------------
#ifndef TRANSIENTDURABILITY_EXPORT_H
#define TRANSIENTDURABILITY_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (TRANSIENTDURABILITY_HAS_DLL)
#  define TRANSIENTDURABILITY_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && TRANSIENTDURABILITY_HAS_DLL */

#if !defined (TRANSIENTDURABILITY_HAS_DLL)
#  define TRANSIENTDURABILITY_HAS_DLL 1
#endif /* ! TRANSIENTDURABILITY_HAS_DLL */

#if defined (TRANSIENTDURABILITY_HAS_DLL) && (TRANSIENTDURABILITY_HAS_DLL == 1)
#  if defined (TRANSIENTDURABILITY_BUILD_DLL)
#    define TransientDurability_Export ACE_Proper_Export_Flag
#    define TRANSIENTDURABILITY_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define TRANSIENTDURABILITY_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* TRANSIENTDURABILITY_BUILD_DLL */
#    define TransientDurability_Export ACE_Proper_Import_Flag
#    define TRANSIENTDURABILITY_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define TRANSIENTDURABILITY_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* TRANSIENTDURABILITY_BUILD_DLL */
#else /* TRANSIENTDURABILITY_HAS_DLL == 1 */
#  define TransientDurability_Export
#  define TRANSIENTDURABILITY_SINGLETON_DECLARATION(T)
#  define TRANSIENTDURABILITY_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* TRANSIENTDURABILITY_HAS_DLL == 1 */

// Set TRANSIENTDURABILITY_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (TRANSIENTDURABILITY_NTRACE)
#  if (ACE_NTRACE == 1)
#    define TRANSIENTDURABILITY_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define TRANSIENTDURABILITY_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !TRANSIENTDURABILITY_NTRACE */

#if (TRANSIENTDURABILITY_NTRACE == 1)
#  define TRANSIENTDURABILITY_TRACE(X)
#else /* (TRANSIENTDURABILITY_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define TRANSIENTDURABILITY_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (TRANSIENTDURABILITY_NTRACE == 1) */

#endif /* TRANSIENTDURABILITY_EXPORT_H */

// End of auto generated file.
