// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p16
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// C:\Users\kuznetsovm\source\repos\OpenDDS\ace_wrappers\TAO\TAO_IDL\be\be_codegen.cpp:461

#ifndef _TAO_IDL_STOCKQUOTERTYPESUPPORTS_V0JE0B_H_
#define _TAO_IDL_STOCKQUOTERTYPESUPPORTS_V0JE0B_H_


#include "StockQuoterTypeSupportC.h"
#include "StockQuoterS.h"
#include "dds/DdsDcpsInfrastructureS.h"
#include "dds/DdsDcpsPublicationS.h"
#include "dds/DdsDcpsSubscriptionExtS.h"
#include "dds/DdsDcpsTopicS.h"
#include "dds/DdsDcpsTypeSupportExtS.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


// TAO_IDL - Generated from
// C:\Users\kuznetsovm\source\repos\OpenDDS\ace_wrappers\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// C:\Users\kuznetsovm\source\repos\OpenDDS\ace_wrappers\TAO\TAO_IDL\be\be_visitor_module\module_sh.cpp:38

namespace POA_StockQuoter
{
  

// TAO_IDL - Generated from
// C:\Users\kuznetsovm\source\repos\OpenDDS\ace_wrappers\TAO\TAO_IDL\be\be_visitor_module\module_sh.cpp:69

} // module StockQuoter

#endif /* ifndef */

