//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.22 at 05:06:17 PM CDT 
//


package org.opendds.modeling.sdk.codegen;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opendds.modeling.sdk.codegen package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Generatorspecification_QNAME = new QName("http://www.opendds.org/modeling/schemas/Generator/1.0", "generatorspecification");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opendds.modeling.sdk.codegen
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Modelfile }
     * 
     */
    public Modelfile createModelfile() {
        return new Modelfile();
    }

    /**
     * Create an instance of {@link Targetdir }
     * 
     */
    public Targetdir createTargetdir() {
        return new Targetdir();
    }

    /**
     * Create an instance of {@link Genspec }
     * 
     */
    public Genspec createGenspec() {
        return new Genspec();
    }

    /**
     * Create an instance of {@link Gencontrol }
     * 
     */
    public Gencontrol createGencontrol() {
        return new Gencontrol();
    }

    /**
     * Create an instance of {@link Instancespec }
     * 
     */
    public Instancespec createInstancespec() {
        return new Instancespec();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Genspec }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opendds.org/modeling/schemas/Generator/1.0", name = "generatorspecification")
    public JAXBElement<Genspec> createGeneratorspecification(Genspec value) {
        return new JAXBElement<Genspec>(_Generatorspecification_QNAME, Genspec.class, null, value);
    }

}
