/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

// Struct with one key
module XYZ {

  struct Nested {
    long subject_id;
  };

#pragma DCPS_DATA_TYPE "XYZ::Message"
#pragma DCPS_DATA_KEY "XYZ::Message nest"

  struct Message {
    Nested nest;
  };
};
