/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

// Struct with one key
module XYZ {

  @topic
  struct Message {
    @key
    long subject_id;
  };
};
