/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

// Struct with one key
module XYZ {

#pragma DCPS_DATA_TYPE "XYZ::Message"
#pragma DCPS_DATA_KEY "XYZ::Message subject_idx"

  struct Message {
    long subject_id;
  };
};
