/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

// Struct with one key
module XYZ {

  typedef long LongType;
#pragma DCPS_DATA_TYPE "XYZ::Message"
#pragma DCPS_DATA_KEY "XYZ::Message subject_id[1]"

  struct Message {
    LongType subject_id;
  };
};
