/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

// Struct with the key in a struct field located within an array
module Messenger10 {

  typedef long CountType;

  @topic
  struct Message {
    @key
    string text;
    @key
    CountType count;
  };
};

// Struct with a bound key length exactly 16 bytes
module Messenger11 {

  @topic
  struct Message {
    @key
    long long_1;
    @key
    long long_2;
    @key
    long long_3;
    @key
    long long_4;
  };
};

// Struct with a bound key length greater than 16 bytes
module Messenger12 {

  @topic
  struct Message {
    @key
    long long_1;
    @key
    long long_2;
    @key
    long long_3;
    @key
    long long_4;
    @key
    long long_5;
  };
};
