/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

// Struct with array element key
module Messenger7 {

  typedef long ResponseArray[3];

  struct HeaderType {
    string from;
    string subject;
    long subject_id;
  };
#pragma DCPS_DATA_TYPE "Messenger7::Message"
#pragma DCPS_DATA_KEY "Messenger7::Message responses[0]"

  struct Message {
    HeaderType header;
    string text;
    long   count;
    ResponseArray responses;
  };
};

// Struct with nested struct containing an array element key
module Messenger8 {

  typedef long ResponseArray[10];

  struct HeaderType {
    string from;
    string subject;
    long subject_id;
    ResponseArray responses;
  };
#pragma DCPS_DATA_TYPE "Messenger8::Message"
#pragma DCPS_DATA_KEY "Messenger8::Message header.responses[0]"

  struct Message {
    HeaderType header;
    string text;
    long   count;
  };
};

// Struct with the key in a struct field located within an array
module Messenger9 {

  struct HeaderType {
    string from;
    string subject;
    long subject_id;
  };
  typedef HeaderType HeaderTypeArray[2];

#pragma DCPS_DATA_TYPE "Messenger9::Message"
#pragma DCPS_DATA_KEY "Messenger9::Message headers[1].subject_id"

  struct Message {
    HeaderTypeArray headers;
    string text;
    long   count;
  };
};

// Struct with the key in a struct field located within an array
module Messenger10 {

  typedef long CountType;
#pragma DCPS_DATA_TYPE "Messenger10::Message"
#pragma DCPS_DATA_KEY "Messenger10::Message count"
#pragma DCPS_DATA_KEY "Messenger10::Message text"

  struct Message {
    string text;
    CountType count;
  };
};

// Struct with a bound key length exactly 16 bytes
module Messenger11 {

#pragma DCPS_DATA_TYPE "Messenger11::Message"
#pragma DCPS_DATA_KEY "Messenger11::Message long_1"
#pragma DCPS_DATA_KEY "Messenger11::Message long_2"
#pragma DCPS_DATA_KEY "Messenger11::Message long_3"
#pragma DCPS_DATA_KEY "Messenger11::Message long_4"

  struct Message {
    long long_1;
    long long_2;
    long long_3;
    long long_4;
  };
};

// Struct with a bound key length greater than 16 bytes
module Messenger12 {

#pragma DCPS_DATA_TYPE "Messenger12::Message"
#pragma DCPS_DATA_KEY "Messenger12::Message long_1"
#pragma DCPS_DATA_KEY "Messenger12::Message long_2"
#pragma DCPS_DATA_KEY "Messenger12::Message long_3"
#pragma DCPS_DATA_KEY "Messenger12::Message long_4"
#pragma DCPS_DATA_KEY "Messenger12::Message long_5"

  struct Message {
    long long_1;
    long long_2;
    long long_3;
    long long_4;
    long long_5;
  };
};
