//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.29 at 03:59:20 PM CDT 
//


package org.opendds.modeling.sdk.codegen;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for genspec complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="genspec">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="source" type="{http://www.opendds.org/modeling/schemas/Generator/1.0}modelfile"/>
 *         &lt;element name="targets" type="{http://www.opendds.org/modeling/schemas/Generator/1.0}targetdir"/>
 *         &lt;element name="specs" type="{http://www.opendds.org/modeling/schemas/Generator/1.0}instancespec"/>
 *         &lt;element name="controls" type="{http://www.opendds.org/modeling/schemas/Generator/1.0}gencontrol"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "genspec", propOrder = {
    "sourceOrTargetsOrSpecs"
})
public class Genspec {

    @XmlElements({
        @XmlElement(name = "specs", type = Instancespec.class),
        @XmlElement(name = "targets", type = Targetdir.class),
        @XmlElement(name = "controls", type = Gencontrol.class),
        @XmlElement(name = "source", type = Modelfile.class)
    })
    protected List<Object> sourceOrTargetsOrSpecs;

    /**
     * Gets the value of the sourceOrTargetsOrSpecs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceOrTargetsOrSpecs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceOrTargetsOrSpecs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Instancespec }
     * {@link Targetdir }
     * {@link Gencontrol }
     * {@link Modelfile }
     * 
     * 
     */
    public List<Object> getSourceOrTargetsOrSpecs() {
        if (sourceOrTargetsOrSpecs == null) {
            sourceOrTargetsOrSpecs = new ArrayList<Object>();
        }
        return this.sourceOrTargetsOrSpecs;
    }

}
