
#include "tao/orb.idl"

module Xyz {

  typedef sequence<float> FloatSeq;

  // Example user defined "Foo" structure
  @topic
  struct Foo {
    @key
    long  data_source;  // the instance key
    float x;
    float y;
    FloatSeq values;
  };

  // Example user defined "FooNoKey" structure
  @topic
  struct FooNoKey {
    long  data_source;
    float x;
    float y;
    FloatSeq values;
  };
};
