// -*- C++ -*-
//

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// .\be\be_codegen.cpp:951

#ifndef DCPSDATAREADERI_H_
#define DCPSDATAREADERI_H_

#include "dds/DCPS/DataReaderCallbacks.h"
#include "dds/DCPS/Definitions.h"

#include "DiscReceivedCalls.h"

#include "dds/DCPS/Discovery.h"

#include <vector>

#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

class TAO_DDS_DCPSDataReader_i
  : public OpenDDS::DCPS::DataReaderCallbacks
{
public:
  enum Called { ENABLE_SPECIFIC, ADD_ASSOC, ASSOC_COMPLETE, REM_ASSOC, UPDATE_INCOMP_QOS };

  TAO_DDS_DCPSDataReader_i (void);

  virtual ~TAO_DDS_DCPSDataReader_i (void);


  virtual ::DDS::ReturnCode_t enable_specific (
      ) { received_.received(DiscReceivedCalls::ENABLE_SPECIFIC); return ::DDS::RETCODE_OK;};

  virtual void add_association (
      const ::OpenDDS::DCPS::RepoId& yourId,
      const OpenDDS::DCPS::WriterAssociation& writer,
      bool active);

  virtual void association_complete(const OpenDDS::DCPS::RepoId& /*remote_id*/) { received_.received(DiscReceivedCalls::ASSOC_COMPLETE); }

  virtual void remove_associations (
      const OpenDDS::DCPS::WriterIdSeq & writers,
      ::CORBA::Boolean notify_lost
    );

  virtual void update_incompatible_qos (
      const OpenDDS::DCPS::IncompatibleQosStatus & status
    );

  virtual void inconsistent_topic() {}

  virtual void signal_liveliness(const OpenDDS::DCPS::RepoId& /*remote_participant*/) { }

  DiscReceivedCalls& received()
    {
      return received_;
    }
  OpenDDS::DCPS::Discovery* disco_;
  DDS::DomainId_t domainId_;
  ::OpenDDS::DCPS::RepoId participantId_;
private:
  DiscReceivedCalls received_;
};


#endif /* DCPSDATAREADERI_H_  */
