#include "tao/TAO_Export.h"
#include "ace/CDR_Base.h"

// This file contains stubbed-out functions that are required to link binaries
// that use code generated by tao_idl.  We do not expect these functions to be
// called when using the OpenDDS subset (local interfaces, structs, etc.).

class TAO_Resource_Factory;

class TAO_Export TAO_ORB_Core {
public:
  TAO_Resource_Factory* resource_factory();
};

TAO_Resource_Factory* TAO_ORB_Core::resource_factory()
{
  return 0;
}

class TAO_Export TAO_OutputCDR {
public:
  bool fragment_stream(ACE_CDR::ULong, ACE_CDR::ULong);
};

bool TAO_OutputCDR::fragment_stream(ACE_CDR::ULong, ACE_CDR::ULong)
{
  return false;
}

namespace IOP {
  class TAO_Export TaggedProfileSeq {
    ~TaggedProfileSeq();
  };
}

IOP::TaggedProfileSeq::~TaggedProfileSeq()
{
}
