#include "tao/ORB_Core.h"

// This file contains stubbed-out functions that are required to link binaries
// that use code generated by tao_idl.  We do not expect these functions to be
// called when using the OpenDDS subset (local interfaces, structs, etc.).

TAO_Resource_Factory* TAO_ORB_Core::resource_factory()
{
  return 0;
}

bool TAO_OutputCDR::fragment_stream(ACE_CDR::ULong, ACE_CDR::ULong)
{
  return false;
}

IOP::TaggedProfileSeq::~TaggedProfileSeq()
{
}
