/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

#include <dds/DdsDcpsCore.idl>

module SecurityAttributes {

  @topic
  struct Message {
    @key
    long subject_id;
    long count;
    string subject;
    string from;
    string text;
    DDS::OctetSeq extra_space;
  };
};
