
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl SecurityAttributes
// ------------------------------
#ifndef SECURITYATTRIBUTES_EXPORT_H
#define SECURITYATTRIBUTES_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (SECURITYATTRIBUTES_HAS_DLL)
#  define SECURITYATTRIBUTES_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && SECURITYATTRIBUTES_HAS_DLL */

#if !defined (SECURITYATTRIBUTES_HAS_DLL)
#  define SECURITYATTRIBUTES_HAS_DLL 1
#endif /* ! SECURITYATTRIBUTES_HAS_DLL */

#if defined (SECURITYATTRIBUTES_HAS_DLL) && (SECURITYATTRIBUTES_HAS_DLL == 1)
#  if defined (SECURITYATTRIBUTES_BUILD_DLL)
#    define SecurityAttributes_Export ACE_Proper_Export_Flag
#    define SECURITYATTRIBUTES_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define SECURITYATTRIBUTES_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* SECURITYATTRIBUTES_BUILD_DLL */
#    define SecurityAttributes_Export ACE_Proper_Import_Flag
#    define SECURITYATTRIBUTES_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define SECURITYATTRIBUTES_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* SECURITYATTRIBUTES_BUILD_DLL */
#else /* SECURITYATTRIBUTES_HAS_DLL == 1 */
#  define SecurityAttributes_Export
#  define SECURITYATTRIBUTES_SINGLETON_DECLARATION(T)
#  define SECURITYATTRIBUTES_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* SECURITYATTRIBUTES_HAS_DLL == 1 */

// Set SECURITYATTRIBUTES_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (SECURITYATTRIBUTES_NTRACE)
#  if (ACE_NTRACE == 1)
#    define SECURITYATTRIBUTES_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define SECURITYATTRIBUTES_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !SECURITYATTRIBUTES_NTRACE */

#if (SECURITYATTRIBUTES_NTRACE == 1)
#  define SECURITYATTRIBUTES_TRACE(X)
#else /* (SECURITYATTRIBUTES_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define SECURITYATTRIBUTES_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (SECURITYATTRIBUTES_NTRACE == 1) */

#endif /* SECURITYATTRIBUTES_EXPORT_H */

// End of auto generated file.
