#include "Builder.idl"

module Stool {

  typedef sequence<octet> OctetSeq;

  // A common defintion of information required for audit purposes (when / where / who / why etc)
  struct AuditInfo {
    Builder::TimeStamp time;
    string system;
    string user;
    string source;
  };

  typedef sequence<AuditInfo> AuditSeq;

// ---
// Data Section
// ---

#pragma DCPS_DATA_TYPE "Stool::Data"
#pragma DCPS_DATA_KEY  "Stool::Data key"
  struct Data {
    long key;
    long pid;
    long seq;
    long priority;
    AuditInfo created;
    AuditSeq relay_trail;
    OctetSeq buffer;
  };

  struct ActionConfig {
    string name;
    string type;
    Builder::PropertySeq params;
    Builder::StringSeq readers;
    Builder::StringSeq writers;
  };

  typedef sequence<ActionConfig> ActionConfigSeq;

  struct ActionReport {
    Builder::PropertySeq properties;
  };

  typedef sequence<ActionReport> ActionReportSeq;

  struct WorkerConfig {
    Builder::TimeStamp enable_time;
    Builder::TimeStamp start_time;
    Builder::TimeStamp stop_time;
    Builder::ProcessConfig process;
    ActionConfigSeq actions;
    ActionReportSeq action_reports;
  };

  struct WorkerReport {
    unsigned long undermatched_readers;
    unsigned long undermatched_writers;
    Builder::TimeStamp max_discovery_time_delta;
    unsigned long long sample_count;
    double latency_min;
    double latency_max;
    double latency_mean;
    double latency_var_x_sample_count;
  };

};

