
#include "FooDef.idl"

module Xyz {

  // Example user defined "Baz" structure
  // This struct will result in a type support implementation that has no
  // references to basic types so the only place to include the <cstring>
  // header is the CL_STRUCTURE metaclass generator branch.
#ifdef __OPENDDS_IDL_HAS_TOPIC_ANNOTATIONS
  @topic
#else
#  pragma DCPS_DATA_TYPE "Xyz::Baz"
#endif
  struct Baz {
    Bar    a_struct_value;
  };

};

