@topic
struct DefaultType {
  long value;
};

@topic
@::OpenDDS::data_representation(XCDR2)
@::OpenDDS::data_representation(XCDR1)
struct Xcdr2Xcdr1Type {
  long value;
};

@topic
@::OpenDDS::data_representation(XCDR1)
struct Xcdr1Type {
  long value;
};

@topic
@::OpenDDS::data_representation(XCDR2)
struct Xcdr2Type {
  long value;
};

@topic
@::OpenDDS::data_representation(XML)
struct XmlType {
  long value;
};
