
// -*- C++ -*-
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl InconsistentTopic
// ------------------------------
#ifndef INCONSISTENTTOPIC_EXPORT_H
#define INCONSISTENTTOPIC_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (INCONSISTENTTOPIC_HAS_DLL)
#  define INCONSISTENTTOPIC_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && INCONSISTENTTOPIC_HAS_DLL */

#if !defined (INCONSISTENTTOPIC_HAS_DLL)
#  define INCONSISTENTTOPIC_HAS_DLL 1
#endif /* ! INCONSISTENTTOPIC_HAS_DLL */

#if defined (INCONSISTENTTOPIC_HAS_DLL) && (INCONSISTENTTOPIC_HAS_DLL == 1)
#  if defined (INCONSISTENTTOPIC_BUILD_DLL)
#    define InconsistentTopic_Export ACE_Proper_Export_Flag
#    define INCONSISTENTTOPIC_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define INCONSISTENTTOPIC_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* INCONSISTENTTOPIC_BUILD_DLL */
#    define InconsistentTopic_Export ACE_Proper_Import_Flag
#    define INCONSISTENTTOPIC_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define INCONSISTENTTOPIC_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* INCONSISTENTTOPIC_BUILD_DLL */
#else /* INCONSISTENTTOPIC_HAS_DLL == 1 */
#  define InconsistentTopic_Export
#  define INCONSISTENTTOPIC_SINGLETON_DECLARATION(T)
#  define INCONSISTENTTOPIC_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* INCONSISTENTTOPIC_HAS_DLL == 1 */

// Set INCONSISTENTTOPIC_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (INCONSISTENTTOPIC_NTRACE)
#  if (ACE_NTRACE == 1)
#    define INCONSISTENTTOPIC_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define INCONSISTENTTOPIC_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !INCONSISTENTTOPIC_NTRACE */

#if (INCONSISTENTTOPIC_NTRACE == 1)
#  define INCONSISTENTTOPIC_TRACE(X)
#else /* (INCONSISTENTTOPIC_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define INCONSISTENTTOPIC_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (INCONSISTENTTOPIC_NTRACE == 1) */

#endif /* INCONSISTENTTOPIC_EXPORT_H */

// End of auto generated file.
