
module Messenger {

  @topic
  struct Message1 {
    string from;
    string subject;
    @key
    string subject_id;
    string text;
    long   count;
  };
  @topic
  struct Message2 {
    short from;
    double subject;
    @key
    string subject_id;
    string text;
    long   count;
  };
};
