
#include "tao/orb.idl"

module Xyz {

  typedef sequence<float> UnboundedData;

  // Example user defined "Foo" structure
  @topic
  struct Foo {
    @key
    long  a_long_value;
    long  handle_value;
    long  sample_sequence;
    long  writer_id;
    UnboundedData unbounded_data;
  };
};
