
module Xyz {

#pragma DCPS_DATA_TYPE "Xyz::Foo"
#pragma DCPS_DATA_KEY "Xyz::Foo key"

  // Example user defined "Foo" structure
  struct Foo {
    long key;  // the instance key
    char  c;
    float x;
    float y;
  };

};
