#!/bin/bash
if [[ -z "${BASIS}" ]]; then
    docker build --build-arg ACE_CONFIG_OPTION=$ACE_CONFIG_OPTION --build-arg ACE_SOURCE_DIR=$ACE_SOURCE_DIR -t $IMAGE_NAME .
else
    docker build --build-arg BASIS=$BASIS --build-arg= ACE_CONFIG_OPTION=$ACE_CONFIG_OPTION --build-arg ACE_SOURCE_DIR=$ACE_SOURCE_DIR -t $IMAGE_NAME .
fi
