/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */
#include "tao/OctetSeq.pidl"
module Messenger {

#pragma DCPS_DATA_TYPE "Messenger::Message"
#pragma DCPS_DATA_KEY "Messenger::Message writer_id"

  typedef sequence<octet> OctetSeq;

  struct Message {
    string process_id;
    string from;
    long participant_id;
    long writer_id;
    string text;
    long   sample_id;
    OctetSeq data;
  };
};
