#include <tao/LongSeq.pidl>

typedef short Short3Array[3];
typedef short Short2x3Array[2][3];
typedef double Double2x3x4Array[2][3][4];

typedef sequence<long> LongSequence;
typedef sequence<long, 3> Long3Sequence;

typedef struct XYZ_ {
  double x;
  double y;
  double z;
} XYZ;

@topic
struct TestStruct {
  float f;
  XYZ position;

  Short3Array s3arr;
  Short2x3Array s2x3arr;
  Double2x3x4Array d2x3x4arr;

  LongSequence lseq;
  Long3Sequence l3seq;

  // prefix a_ denotes anonymous type fields

  short a_s3arr[3];
  short a_s3arr_2nd[3];
  short a_s2x3arr[2][3];
  double a_d2x3x4arr[2][3][4];

  sequence<long> a_lseq;
  sequence<long> a_lseq_2nd;
  sequence<long, 3> a_l3seq;
  sequence<long, 3> a_l3seq_2nd;
  sequence<long, 5> a_l5seq;
};
