#ifndef ECU_IDL
#define ECU_IDL

#include "engine_specs.idl"
#include "transmission_specs.idl"
#include "fuel_stats.idl"

@topic
struct EcuInfo {
    @key string id;

    EngineTemp oil;
    EngineTemp coolant;
    EngineRpm rpm;
    TransmissionStatus transmission;

    FuelStats calc;
};

#endif /* ECU_IDL */
