// -*- C++ -*-
//
// $Id$
// -*- C++ -*-
//
#include "Writer.h"
#include "../common/TestException.h"
#include "dds/DCPS/transport/framework/ReceivedDataSample.h"
#include "dds/DCPS/Service_Participant.h"
#include "dds/DCPS/Serializer.h"
#include "tests/DCPS/FooType4/FooDefTypeSupportC.h"
#include "tests/DCPS/FooType4/FooDefTypeSupportImpl.h"

const int default_key = 101010;


Writer::Writer(::DDS::DataReader_ptr reader,
               int num_writes_per_thread,
               int multiple_instances,
               int instance_id)
: num_writes_per_thread_(num_writes_per_thread),
  multiple_instances_ (multiple_instances),
  instance_id_(instance_id),
  reader_(reader)
{
}

void
Writer::start ()
{
  ACE_DEBUG((LM_DEBUG,
              ACE_TEXT("(%P|%t) Writer::start \n")));

  try
  {
    OpenDDS::DCPS::DataReaderImpl* dr_servant =
      dynamic_cast<OpenDDS::DCPS::DataReaderImpl*> (reader_);

    ::Xyz::Foo foo;
    foo.x = 0.0 ;
    foo.y = 0.0 ;

    ::OpenDDS::DCPS::SequenceNumber seq ;

    if (!multiple_instances_)
    {
      foo.key = default_key;
    }

    for (int i = 0; i< num_writes_per_thread_; i ++)
    {
      seq++ ;

      foo.x = (float)i ;
      foo.y = (float)i ;

      if (multiple_instances_)
      {
        foo.key = i + 1 ;
      }

      ACE_Time_Value now = ACE_OS::gettimeofday () ;

      ACE_OS::printf ("\"writing\" foo.x = %f foo.y = %f, foo.key = %d\n",
                      foo.x, foo.y, foo.key);
      ::OpenDDS::DCPS::ReceivedDataSample sample ;

      sample.header_.message_length_ = sizeof(foo) ;
      sample.header_.message_id_ = ::OpenDDS::DCPS::SAMPLE_DATA ;
      sample.header_.sequence_ = seq.value_ ;

      // Never do this! Repository ID's should be treated opaquely and
      // may only be generated by the DCPSInfoRepo. This section was
      // converted from legacy code and should be treated as such!
      sample.header_.publication_id_ = OpenDDS::DCPS::create_empty_guid();

      sample.header_.publication_id_.guidPrefix[11] = 1; // participantId = 1
      sample.header_.publication_id_.entityId.entityKind = OpenDDS::DCPS::ENTITYKIND_USER_WRITER_WITH_KEY;
      sample.header_.publication_id_.entityId.entityKey[2] = 1;

      sample.header_.source_timestamp_sec_ =
		  static_cast<ACE_INT32> (now.sec ());
      sample.header_.source_timestamp_nanosec_ = now.usec() * 1000 ;

      sample.sample_ =  new ACE_Message_Block(sizeof(foo)) ;

      ::TAO::DCPS::Serializer ser(sample.sample_) ;
      ser << foo ;

      dr_servant->data_received(sample) ;
    }
  }
  catch (const CORBA::Exception& ex)
  {
    ex._tao_print_exception ("Exception caught in svc:");
  }
}

