module optional {

  typedef sequence<int32> seq_int_t;

  struct OptionalMembers {
    @optional short short_field;
    @optional long long_field;

    // string strOpt;
    //seq_int_t seqOpt;


    // TODO(tyler) should this be possible
    // Code generates a IDL::DistinctType<...>
    // @optional sequence<int32> seqInt;
  };

};
