//
// $Id: Test.idl dczanella@gmail.com $
//

/// Put the interfaces in a module, to avoid global namespace pollution
module Test
{
  /// A very simple interface
  interface CorbaDpShutdown
  {

    /// A method to shutdown the ORB
    /**
     * This method is used to simplify the test shutdown process
     */
    oneway void shutdown ();

    void start();

    void stop();
  };
};
