/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

module NestedTypesTest {

  typedef unsigned long KeyArray[3];

  struct Separated {
    @key
    unsigned long key_;
    KeyArray key2_;
  };

  typedef Separated SeparatedArray[2];

  struct Dot {
    @key
    Separated separated_;
    SeparatedArray separated2_;
  };

  @topic
  struct KeyInNestedStruct {
    @key
    Dot dot_;
  };

  struct StructWithValue {
    @key
    short value;
  };
  typedef StructWithValue MyStructTypedef;

  @topic
  struct TypedefStructKeyStruct {
    @key
    MyStructTypedef my_struct_typedef_key;
  };

  enum msgType_t {
    val1,
    val2
  };

  union msgUnion_t switch (msgType_t) {
    case val1:
      string someString;
    case val2:
      float someFloat;
  };

  @topic
  struct Message {
    @key long subject_id;
    msgUnion_t msgUnion;
  };
};
