<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="OpenDDS"
    nsURI="http://www.opendds.org/schemas/modeling/OpenDDS" nsPrefix="opendds">
  <eClassifiers xsi:type="ecore:EClass" name="Entity" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedEntity" abstract="true" eSuperTypes="#//Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specification" abstract="true" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainEntity" abstract="true" eSuperTypes="#//NamedEntity"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContentFilteredTopic" eSuperTypes="#//TopicDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter_expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiTopic" eSuperTypes="#//TopicDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subscription_expression"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Topic" eSuperTypes="#//DomainEntity #//TopicDescription">
    <eStructuralFeatures xsi:type="ecore:EReference" name="durability_service" eType="#//DurabilityServiceQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transport_priority" eType="#//TransportPriorityQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topic_data" eType="#//TopicDataQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource_limits" eType="#//ResourceLimitsQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reliability" eType="#//ReliabilityQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownership" eType="#//OwnershipQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="liveliness" eType="#//LivelinessQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="history" eType="#//HistoryQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="durability" eType="#//DurabilityQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination_order" eType="#//DestinationOrderQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deadline" eType="#//DeadlineQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="latency_budget" eType="#//LatencyBudgetQosPolicy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopicDescription" abstract="true" eSuperTypes="#//NamedEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//TopicField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Array" eSuperTypes="#//Collection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OBoolean" eSuperTypes="#//Simple"/>
  <eClassifiers xsi:type="ecore:EClass" name="Case" eSuperTypes="#//TopicField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labels" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//TopicField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OChar" eSuperTypes="#//Simple"/>
  <eClassifiers xsi:type="ecore:EClass" name="Collection" abstract="true" eSuperTypes="#//TopicField">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//TopicField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstructedTopicType" abstract="true"
      eSuperTypes="#//TopicField"/>
  <eClassifiers xsi:type="ecore:EClass" name="ODouble" eSuperTypes="#//Simple"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enum" eSuperTypes="#//TopicField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labels" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OFloat" eSuperTypes="#//Simple"/>
  <eClassifiers xsi:type="ecore:EClass" name="Key">
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" lowerBound="1"
        eType="#//KeyField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyField"/>
  <eClassifiers xsi:type="ecore:EClass" name="OLong" eSuperTypes="#//Simple"/>
  <eClassifiers xsi:type="ecore:EClass" name="OLongLong" eSuperTypes="#//Simple"/>
  <eClassifiers xsi:type="ecore:EClass" name="OOctet" eSuperTypes="#//Simple"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence" eSuperTypes="#//Collection"/>
  <eClassifiers xsi:type="ecore:EClass" name="OShort" eSuperTypes="#//Simple"/>
  <eClassifiers xsi:type="ecore:EClass" name="Simple" abstract="true" eSuperTypes="#//TopicField #//KeyField"/>
  <eClassifiers xsi:type="ecore:EClass" name="OString" eSuperTypes="#//Simple"/>
  <eClassifiers xsi:type="ecore:EClass" name="TopicStruct" eSuperTypes="#//ConstructedTopicType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" lowerBound="1"
        upperBound="-1" eType="#//TopicField" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keys" upperBound="-1" eType="#//Key"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopicField" abstract="true" eSuperTypes="#//NamedEntity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Typedef" eSuperTypes="#//TopicField">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TopicField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OULong"/>
  <eClassifiers xsi:type="ecore:EClass" name="OULongLong"/>
  <eClassifiers xsi:type="ecore:EClass" name="Union" eSuperTypes="#//ConstructedTopicType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="switch" lowerBound="1"
        eType="#//TopicField"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" lowerBound="1" eType="#//Case"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OUShort"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataReader" eSuperTypes="#//DataReaderWriter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="topic" lowerBound="1" eType="#//TopicDescription"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reader_data_lifecycle"
        eType="#//ReaderDataLifecycleQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transport_priority" eType="#//TransportPriorityQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="durability_service" eType="#//DurabilityServiceQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownership_strength" eType="#//OwnershipStrengthQosPolicy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataReaderWriter" abstract="true" eSuperTypes="#//DomainEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="durability" eType="#//DurabilityQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination_order" eType="#//DestinationOrderQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deadline" eType="#//DeadlineQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="history" eType="#//HistoryQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user_data" eType="#//UserDataQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource_limits" eType="#//ResourceLimitsQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownership" eType="#//OwnershipQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="liveliness" eType="#//LivelinessQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="latency_budget" eType="#//LatencyBudgetQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reliability" eType="#//ReliabilityQosPolicy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataWriter" eSuperTypes="#//DataReaderWriter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="topic" lowerBound="1" eType="#//Topic"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writer_data_lifecycle"
        eType="#//WriterDataLifecycleQosPolicy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Domain" eSuperTypes="#//NamedEntity"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainParticipant" eSuperTypes="#//DomainEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subscribers" upperBound="-1"
        eType="#//Subscriber" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publishers" upperBound="-1"
        eType="#//Publisher" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity_factory" eType="#//EntityFactoryQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user_data" eType="#//UserDataQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" lowerBound="1"
        eType="#//Domain"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Publisher" eSuperTypes="#//PublisherSubscriber">
    <eStructuralFeatures xsi:type="ecore:EReference" name="writers" lowerBound="1"
        upperBound="-1" eType="#//DataWriter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublisherSubscriber" abstract="true"
      eSuperTypes="#//DomainEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity_factory" eType="#//EntityFactoryQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="presentation" eType="#//PresentationQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group_data" eType="#//GroupDataQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="partition" eType="#//PartitionQosPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transport" lowerBound="1"
        eType="#//Transport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subscriber" eSuperTypes="#//PublisherSubscriber">
    <eStructuralFeatures xsi:type="ecore:EReference" name="readers" lowerBound="1"
        upperBound="-1" eType="#//DataReader" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeadlineQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="period" eType="#//Period"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DestinationOrderQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//DestinationOrderQosPolicyKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DurabilityQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//DurabilityQosPolicyKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DurabilityServiceQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="history_depth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="history_kind" eType="#//HistoryQosPolicyKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_instances" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_samples" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_samples_per_instance"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="service_cleanup_delay"
        eType="#//Period" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityFactoryQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoenable_created_entities"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupDataQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HistoryQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="depth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//HistoryQosPolicyKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LatencyBudgetQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duration" eType="#//Period"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LifespanQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duration" eType="#//Period"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LivelinessQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//LivelinessQosPolicyKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lease_duration" eType="#//Period"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OwnershipQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//OwnershipQosPolicyKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OwnershipStrengthQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PartitionQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentationQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="access_scope" eType="#//PresentationQosPolicyAccessScopeKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coherent_access" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered_access" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QosPolicy" abstract="true" eSuperTypes="#//Specification"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReaderDataLifecycleQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="autopurge_nowriter_samples_delay"
        eType="#//Period" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReliabilityQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ReliabilityQosPolicyKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="max_blocking_time" eType="#//Period"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceLimitsQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_instances" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_samples" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_samples_per_instance"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeBasedFilterQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="minimum_separation" eType="#//Period"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopicDataQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransportPriorityQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserDataQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DestinationOrderQosPolicyKind">
    <eLiterals name="BY_RECEPTION_TIMESTAMP" literal="BY_RECEPTION_TIMESTAMP"/>
    <eLiterals name="BY_SOURCE_TIMESTAMP" value="1" literal="BY_SOURCE_TIMESTAMP"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DurabilityQosPolicyKind">
    <eLiterals name="VOLATILE" literal="VOLATILE"/>
    <eLiterals name="TRANSIENT" value="1" literal="TRANSIENT"/>
    <eLiterals name="TRANSIENT_LOCAL" value="2" literal="TRANSIENT_LOCAL"/>
    <eLiterals name="PERSISTENT" value="3" literal="PERSISTENT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HistoryQosPolicyKind">
    <eLiterals name="KEEP_LAST" literal="KEEP_LAST"/>
    <eLiterals name="KEEP_ALL" value="1" literal="KEEP_ALL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LivelinessQosPolicyKind">
    <eLiterals name="AUTOMATIC" literal="AUTOMATIC"/>
    <eLiterals name="MANUAL_BY_PARTICIPANT" value="1" literal="MANUAL_BY_PARTICIPANT"/>
    <eLiterals name="MANUAL_BY_TOPIC" value="2" literal="MANUAL_BY_TOPIC"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OwnershipQosPolicyKind">
    <eLiterals name="SHARED" literal="SHARED"/>
    <eLiterals name="EXCLUSIVE" value="1" literal="EXCLUSIVE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Period">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seconds" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nanoseconds" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PresentationQosPolicyAccessScopeKind">
    <eLiterals name="INSTANCE" literal="INSTANCE"/>
    <eLiterals name="TOPIC" value="1" literal="TOPIC"/>
    <eLiterals name="GROUP" value="2" literal="GROUP"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReliabilityQosPolicyKind">
    <eLiterals name="BEST_EFFORT" literal="BEST_EFFORT"/>
    <eLiterals name="RELIABLE" value="1" literal="RELIABLE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WriterDataLifecycleQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autodispose_unregistered_instances"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationTarget" eSuperTypes="#//Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="component_type" lowerBound="1"
        eType="#//ComponentType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" lowerBound="1"
        eType="#//LanguageType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="platform" lowerBound="1"
        eType="#//PlatformType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" lowerBound="1"
        upperBound="-1" eType="#//DomainParticipant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="service_arguments" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComponentType">
    <eLiterals name="EXECUTABLE"/>
    <eLiterals name="SHARED_LIBRARY" value="1"/>
    <eLiterals name="STATIC_LIBRARY" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LanguageType">
    <eLiterals name="CXX"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PlatformType">
    <eLiterals name="MPC_CDT"/>
    <eLiterals name="MPC_GNUACE" value="1"/>
    <eLiterals name="MPC_NMAKE" value="2"/>
    <eLiterals name="MPC_VC71" value="3"/>
    <eLiterals name="MPC_VC8" value="4"/>
    <eLiterals name="MPC_VC9" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transport_id" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
</ecore:EPackage>
