module UnionTopic {
  struct Candidate_t {
    string name;
    long votes;
  };
  typedef sequence<Candidate_t> CandidateSeq_t;

  struct ElectionStatus_t {
    CandidateSeq_t candidates;
    long total_votes;
  };

  struct ElectionResult_t {
    Candidate_t winner;
    long total_votes;
  };

  enum ElectionNewsType_t {
    ELECTION_NEW_CANDIDATE,
    ELECTION_STATUS,
    ELECTION_RESULT
  };

  @topic
  union ElectionNews_t switch (@key ElectionNewsType_t) {
  case ELECTION_NEW_CANDIDATE:
    Candidate_t new_candidate;
  case ELECTION_STATUS:
    ElectionStatus_t status;
  case ELECTION_RESULT:
    ElectionResult_t result;
  };
};
