
//#include "orbsvcs/dds/DdsDcpsInfrastructure.idl"
//#include "orbsvcs/dds/DdsDcpsTopic.idl"
//#include "orbsvcs/dds/DdsDcpsDataWriterRemote.idl"
//#include "orbsvcs/dds/DdsDcpsDataReaderRemote.idl"
#include "dds/DdsDcpsTypeSupportTao.idl"


interface MyTypeSupport : TAO::DCPS::TypeSupport {
    DDS::ReturnCode_t register_type(
		in DDS::DomainParticipant participant,
		in string type_name);
};


