module org {
  module omg {
    module dds {
      module demo {

        @topic
        @appendable
        struct ShapeType {
          @key string<128> color;
          int32 x;
          int32 y;
          int32 shapesize;
        };

      };
    };
  };
};
