<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="InstanceTraits"
    nsURI="http://www.opendds.org/modeling/schemas/OpenDDS/1.0" nsPrefix="opendds">
  <eClassifiers xsi:type="ecore:EClass" name="Transports">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transport" upperBound="-1"
        eType="#//TransportConfig" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransportConfig" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transportId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="swap_bytes" eType="#//BooleanConfigParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queue_messages_per_pool"
        eType="#//IntegerConfigParam" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queue_initial_pools" eType="#//IntegerConfigParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="max_packet_size" eType="#//IntegerConfigParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="max_samples_per_packet"
        eType="#//IntegerConfigParam" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optimum_packet_size" eType="#//IntegerConfigParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thread_per_connection"
        eType="#//BooleanConfigParam" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datalink_release_delay"
        eType="#//IntegerConfigParam" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datalink_control_chunks"
        eType="#//IntegerConfigParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TcpConfig" eSuperTypes="#//TransportConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transport_type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" defaultValueLiteral="SimpleTcp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="local_address_str" eType="#//StringConfigParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enable_nagle_algorithm"
        eType="#//BooleanConfigParam" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conn_retry_initial_delay"
        eType="#//StringConfigParam" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conn_retry_backoff_multiplier"
        eType="#//FloatConfigParam" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conn_retry_attempts" eType="#//IntegerConfigParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="max_output_pause_period"
        eType="#//IntegerConfigParam" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="passive_reconnect_duration"
        eType="#//IntegerConfigParam" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="passive_connect_duration"
        eType="#//IntegerConfigParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MulticastConfig" eSuperTypes="#//TransportConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transport_type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" defaultValueLiteral="multicast"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="default_to_ipv6" eType="#//BooleanConfigParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port_offset" eType="#//IntegerConfigParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group_address" eType="#//StringConfigParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reliable" eType="#//BooleanConfigParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="syn_backoff" eType="#//FloatConfigParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="syn_interval" eType="#//IntegerConfigParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="syn_timeout" eType="#//IntegerConfigParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nak_depth" eType="#//IntegerConfigParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nak_interval" eType="#//IntegerConfigParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nak_timeout" eType="#//IntegerConfigParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ttl" eType="#//IntegerConfigParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rcv_buffer_size" eType="#//IntegerConfigParam"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UdpConfig" eSuperTypes="#//TransportConfig">
    <eStructuralFeatures xsi:type="ecore:EReference" name="local_address_str" eType="#//StringConfigParam"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanConfigParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerConfigParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringConfigParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatConfigParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
</ecore:EPackage>
