<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="InstanceTraits"
    nsURI="http://www.opendds.org/modeling/schemas/OpenDDS/1.0" nsPrefix="opendds">
  <eClassifiers xsi:type="ecore:EClass" name="Transports">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transport" upperBound="-1"
        eType="#//TransportConfig" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransportConfig" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transportId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="swap_bytes" eType="#//BooleanConfigParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queue_messages_per_pool"
        eType="#//IntegerConfigParam" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queue_initial_pools" eType="#//IntegerConfigParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="max_packet_size" eType="#//IntegerConfigParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="max_samples_per_packet"
        eType="#//IntegerConfigParam" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optimum_packet_size" eType="#//IntegerConfigParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thread_per_connection"
        eType="#//BooleanConfigParam" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datalink_release_delay"
        eType="#//IntegerConfigParam" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datalink_control_chunks"
        eType="#//IntegerConfigParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TcpConfig" eSuperTypes="#//TransportConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transport_type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" defaultValueLiteral="SimpleTcp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="local_address_str" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="127.0.0.1" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enable_nagle_algorithm"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conn_retry_initial_delay"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="500"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conn_retry_backoff_multiplier"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="2.0"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conn_retry_attempts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="3" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_output_pause_period"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passive_reconnect_duration"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="2000"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passive_connect_duration"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MulticastConfig" eSuperTypes="#//TransportConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transport_type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" defaultValueLiteral="multicast"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default_to_ipv6" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port_offset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="10000"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="group_address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reliable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="syn_backoff" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="2.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="syn_interval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="250"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="syn_timeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="30000"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nak_depth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="32"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nak_interval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="500"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nak_timeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="30000"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ttl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rcv_buffer_size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UdpConfig" eSuperTypes="#//TransportConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="local_address_str" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="127.0.0.1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanConfigParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerConfigParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
