<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="InstanceTraits"
    nsURI="http://www.opendds.org/modeling/schemas/OpenDDS/1.0" nsPrefix="opendds">
  <eClassifiers xsi:type="ecore:EClass" name="Transports">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transport" upperBound="-1"
        eType="#//TransportConfig" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransportConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transportId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
  </eClassifiers>
</ecore:EPackage>
