
module profilingTest {

  typedef sequence<octet> OctetSeq;
  @topic
  struct testMsg {
    @key
    unsigned long         msgID;
    unsigned long         count;
    OctetSeq       contents;
  };



};
