#ifndef DEFAULTINSTANCETRAITS_H
#define DEFAULTINSTANCETRAITS_H

#include "dds/DCPS/transport/framework/TransportDefs.h"

namespace OpenDDS { namespace Model {

  /// Define default values and behaviors so instance traits only need to
  /// implement those that are different from the default.
  struct DefaultInstanceTraits {
    /// Transport key values in the model are relative to this base.
    //enum { transport_key_base = 0 };

    //void transport_config(OpenDDS::DCPS::TransportIdType /*id*/) {}
  };

  // example of what might be generated by running xslt on the .codegen
  //struct ExampleInstanceTraits : DefaultInstanceTraits {
    //void transport_config(OpenDDS::DCPS::TransportIdType id);
  //};


} } // End of namespace OpenDDS::Model

#endif /* DEFAULTINSTANCETRAITS_H */

