# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py
  builder: html
  # We have a separate "strict" job on GitHub for this
  fail_on_warning: false

# NOTE: These are in addition to the main HTML
formats:
  - pdf

python:
  install:
    - requirements: docs/requirements.txt
