/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

#pragma DCPS_DATA_TYPE "TestMessage"
#pragma DCPS_DATA_KEY "TestMessage key"

struct TestMessage {
  long key;
  string message;
};
