// -*- C++ -*-
//

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// .\be\be_codegen.cpp:1014

#include "TopicListener.h"

OPENDDS_DCPS_TopicListener_i::OPENDDS_DCPS_TopicListener_i (void)
  {
    last_status_.total_count = 0;
    last_status_.total_count_change = 0;
  }

OPENDDS_DCPS_TopicListener_i::~OPENDDS_DCPS_TopicListener_i (void)
  {
  }

void OPENDDS_DCPS_TopicListener_i::on_inconsistent_topic (
    ::DDS::Topic_ptr ,
    const ::DDS::InconsistentTopicStatus & status
  )
  {
    last_status_ = status;
  }

