
module Test {

typedef sequence<octet> OctetSeq;

#pragma DCPS_DATA_TYPE "Test::Data"
#pragma DCPS_DATA_KEY  "Test::Data priority"
  struct Data {
    long     priority;
    long     pid;
    long     seq;
    OctetSeq buffer;
  };

};
