#include <tao/OctetSeq.pidl>

@topic
struct Property_1 {
  @key long key;
  long value;
};

// TODO: remove if not needed
@topic
struct Property_2 {
  @key long key;
  string value;
};

@topic
@appendable
@OpenDDS::data_representation(XCDR2)
struct AppendableStruct {
  @key long key;
};

@topic
@appendable
@OpenDDS::data_representation(XCDR2)
struct AdditionalPostfixFieldStruct {
  @key long key;
  long additional_field;
};

@topic
@appendable
@OpenDDS::data_representation(XCDR2)
struct AdditionalPrefixFieldStruct {
  long additional_field;
  @key long key;
};

@topic
@mutable
@OpenDDS::data_representation(XCDR2)
struct ModifiedMutableStruct {
  @id(2) long additional_field;
  @id(1) @key long key;
};

@topic
@mutable
@OpenDDS::data_representation(XCDR2)
struct MutableStruct {
  @id(1) @key long key;
  @id(2) long additional_field;
};


// Unions

enum UnionDisc {
  E_KEY,
  E_OCTET_FIELD,
  E_ADDITIONAL_FIELD
};

@topic
@mutable
@OpenDDS::data_representation(XCDR2)
union MutableUnion switch (UnionDisc) {
case E_KEY:
  @id(6) long key;
case E_OCTET_FIELD:
  @id(8) octet octet_field;
case E_ADDITIONAL_FIELD:
  @id(12) long additional_field;
};

@topic
@mutable
@OpenDDS::data_representation(XCDR2)
union ModifiedMutableUnion switch (UnionDisc) {
case E_KEY:
  @id(6) long key;
case E_ADDITIONAL_FIELD:
  @id(12) long additional_field;
};