#include <tao/OctetSeq.pidl>

@topic
struct Property_1 {
  @key long key;
  long value;
};

// TODO: remove if not needed
@topic
struct Property_2 {
  @key long key;
  string value;
};

// Final structues

@topic
@final
struct FinalStruct {
  short x;
  short y;
  short z;
};

@topic
@final
struct ModifiedFinalStruct {
  short x;
  short y;
};

// Appendable structues

@topic
@appendable
struct AppendableStruct {
  @key long key;
};

@topic
@appendable
struct AdditionalPostfixFieldStruct {
  @key long key;
  long additional_field;
};

@topic
@appendable
struct AdditionalPrefixFieldStruct {
  long additional_field;
  @key long key;
};

// Mutable structues

@topic
@mutable
struct MutableStruct {
  @id(1) @key long key;
  @id(2) long additional_field;
};

@topic
@mutable
struct ModifiedMutableStruct {
  @id(2) long additional_field;
  @id(1) @key long key;
};

// Unions

enum UnionDisc {
  E_KEY,
  E_OCTET_FIELD,
  E_ADDITIONAL_FIELD
};

@topic
@mutable
union MutableUnion switch (UnionDisc) {
case E_KEY:
  @id(6) long key;
case E_OCTET_FIELD:
  @id(8) octet octet_field;
case E_ADDITIONAL_FIELD:
  @id(12) long additional_field;
};

@topic
@mutable
union ModifiedMutableUnion switch (UnionDisc) {
case E_KEY:
  @id(6) long key;
case E_ADDITIONAL_FIELD:
  @id(12) long additional_field;
};

// Tryconstruct

typedef string<20> str20;
typedef string<64> str64;

@topic
@mutable
struct Trim64Struct {
  @try_construct(TRIM) str64 trim_string;
};

@topic
@mutable
struct Trim20Struct {
  @try_construct(TRIM) str20 trim_string;
};

// Dependencies

@appendable
struct NestedStruct {
  long additional_field;
};

@topic
@appendable
struct AppendableStructWithDependency {
  @key long key;
  NestedStruct additional_nested_struct;
};
