#include <tao/OctetSeq.pidl>

@topic
struct Property_1 {
  @key long key;
  long value;
};

// TODO: remove if not needed
@topic
struct Property_2 {
  @key long key;
  string value;
};

@topic
@appendable
@OpenDDS::data_representation(XCDR2)
struct AppendableStruct {
  @key long key;
};

@topic
@appendable
@OpenDDS::data_representation(XCDR2)
struct AdditionalPostfixFieldStruct {
  @key long key;
  long additional_field;
};

@topic
@appendable
@OpenDDS::data_representation(XCDR2)
struct AdditionalPrefixFieldStruct {
  long additional_field;
  @key long key;
};

@topic
@mutable
@OpenDDS::data_representation(XCDR2)
struct AlteredMutableStruct {
  @id(2) long additional_field;
  @id(1) @key long key;
};

@topic
@mutable
@OpenDDS::data_representation(XCDR2)
struct MutableStruct {
  @id(1) @key long key;
  @id(2) long additional_field;
};
