<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="opendds"
    nsURI="http://www.opendds.org/schemas/modeling/OpenDDS" nsPrefix="opendds">
  <eClassifiers xsi:type="ecore:EClass" name="DdsSpecification" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseClass" ordered="false"
        lowerBound="1" eType="ecore:EClass uml.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DdsProperty" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseProperty" ordered="false"
        lowerBound="1" eType="ecore:EClass uml.ecore#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QosProperty" eSuperTypes="#//DdsProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="QosPolicy" abstract="true" eSuperTypes="#//DdsSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="TopicStruct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseClass" ordered="false"
        lowerBound="1" eType="ecore:EClass uml.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopicField" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseProperty" ordered="false"
        lowerBound="1" eType="ecore:EClass uml.ecore#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Topic" eSuperTypes="#//DdsProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" ordered="false"
        lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false" lowerBound="1"
        eType="#//TopicKind" defaultValueLiteral="STANDARD"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1"
        eType="#//TopicStruct"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TopicKind">
    <eLiterals name="STANDARD"/>
    <eLiterals name="MULTI_TOPIC" value="1"/>
    <eLiterals name="CONTENT_FILTERED" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IdlTypedef" eSuperTypes="#//TopicField"/>
  <eClassifiers xsi:type="ecore:EClass" name="IdlPrimitive" eSuperTypes="#//TopicField"/>
  <eClassifiers xsi:type="ecore:EClass" name="IdlStruct" eSuperTypes="#//TopicField"/>
  <eClassifiers xsi:type="ecore:EClass" name="IdlSequence" eSuperTypes="#//TopicField"/>
  <eClassifiers xsi:type="ecore:EClass" name="IdlUnion" eSuperTypes="#//TopicField"/>
  <eClassifiers xsi:type="ecore:EClass" name="IdlEnum" eSuperTypes="#//TopicField"/>
  <eClassifiers xsi:type="ecore:EClass" name="IdlArray" eSuperTypes="#//TopicField"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataReader">
    <eStructuralFeatures xsi:type="ecore:EReference" name="basePort" ordered="false"
        lowerBound="1" eType="ecore:EClass uml.ecore#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataWriter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="basePort" ordered="false"
        lowerBound="1" eType="ecore:EClass uml.ecore#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Publisher" eSuperTypes="#//DdsProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="Subscriber" eSuperTypes="#//DdsProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="Domain" eSuperTypes="#//DdsProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainParticipant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseComponent" ordered="false"
        lowerBound="1" eType="ecore:EClass uml.ecore#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" ordered="false"
        lowerBound="1" eType="#//Domain"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HistoryQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="depth" ordered="false"
        lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//Long" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false" lowerBound="1"
        eType="ecore:EEnum openddstypes.ecore#//HistoryQosPolicyKind" defaultValueLiteral="KEEP_LAST"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LifespanQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" ordered="false"
        lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//Duration_t" defaultValueLiteral="{0, 0}"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OwnershipQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false" lowerBound="1"
        eType="ecore:EEnum openddstypes.ecore#//OwnershipQosPolicyKind" defaultValueLiteral="SHARED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OsQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//Long" defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WdlQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autodispose_unregistered_instances"
        ordered="false" lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//Boolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RdlQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autopurge_nowriter_samples_delay"
        ordered="false" lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//Duration_t"
        defaultValueLiteral="{0, 0}"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UdQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LbQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" ordered="false"
        lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//Duration_t" defaultValueLiteral="{0, 0}"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GdQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TdQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EfQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoenable_created_entities"
        ordered="false" lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//Boolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeadlineQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period" ordered="false"
        lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//Duration_t" defaultValueLiteral="{0, 0}"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RlQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_instances" ordered="false"
        lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//Long" defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_samples" ordered="false"
        lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//Long" defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_samples_per_instance"
        ordered="false" lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//Long"
        defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentationQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="access_scope" ordered="false"
        lowerBound="1" eType="ecore:EEnum openddstypes.ecore#//PresentationQosPolicyAccessScopeKind"
        defaultValueLiteral="INSTANCE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coherent_access" ordered="false"
        lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//Boolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered_access" ordered="false"
        lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//Boolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PartitionQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType openddstypes.ecore#//String" defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReliabilityQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false" lowerBound="1"
        eType="ecore:EEnum openddstypes.ecore#//ReliabilityQosPolicyKind" defaultValueLiteral="BEST_EFFORT"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_blocking_time" ordered="false"
        lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//Duration_t" defaultValueLiteral="{0, 0}"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DsQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="history_depth" ordered="false"
        lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//Long" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="history_kind" ordered="false"
        lowerBound="1" eType="ecore:EEnum openddstypes.ecore#//HistoryQosPolicyKind"
        defaultValueLiteral="KEEP_LAST"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_instances" ordered="false"
        lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//Long" defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_samples" ordered="false"
        lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//Long" defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_samples_per_instance"
        ordered="false" lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//Long"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="service_cleanup_delay"
        ordered="false" lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//Duration_t"
        defaultValueLiteral="{0, 0}"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LivelinessQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false" lowerBound="1"
        eType="ecore:EEnum openddstypes.ecore#//LivelinessQosPolicyKind" defaultValueLiteral="AUTOMATIC"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lease_duration" ordered="false"
        lowerBound="1" eType="ecore:EDataType openddstypes.ecore#//Duration_t" defaultValueLiteral="{0, 0}"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DurabilityQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false" lowerBound="1"
        eType="ecore:EEnum openddstypes.ecore#//DurabilityQosPolicyKind" defaultValueLiteral="VOLATILE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoQosPolicy" eSuperTypes="#//QosPolicy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false" lowerBound="1"
        eType="ecore:EEnum openddstypes.ecore#//DestinationOrderQosPolicyKind" defaultValueLiteral="BY_RECEPTION_TIMESTAMP"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DdsAppTarget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseComponent" ordered="false"
        lowerBound="1" eType="ecore:EClass uml.ecore#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participant" ordered="false"
        lowerBound="1" eType="#//DomainParticipant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="language" ordered="false"
        lowerBound="1" eType="#//LanguageType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="platform" ordered="false"
        lowerBound="1" eType="#//PlatformType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentType" ordered="false"
        lowerBound="1" eType="#//ComponentType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LanguageType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseEnumeration" ordered="false"
        lowerBound="1" eType="ecore:EClass uml.ecore#//Enumeration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlatformType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseEnumeration" ordered="false"
        lowerBound="1" eType="ecore:EClass uml.ecore#//Enumeration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseEnumeration" ordered="false"
        lowerBound="1" eType="ecore:EClass uml.ecore#//Enumeration"/>
  </eClassifiers>
</ecore:EPackage>
