/*
 * $Id$
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

#ifndef _RTPS_RTPSBASEMESSAGETYPES_IDL_
#define _RTPS_RTPSBASEMESSAGETYPES_IDL_

#include "../../DdsDcpsGuid.idl"

module OpenDDS {
  module RTPS {

    typedef DCPS::GuidPrefix_t GuidPrefix_t;
    typedef DCPS::EntityId_t EntityId;
    typedef DCPS::GUID_t GUID_t;

    typedef sequence<GUID_t> GUIDSeq;

    /* Type used to hold a timestamp. */
    struct Time_t {
      long seconds;
      unsigned long fraction;
    };
    typedef Time_t Timestamp_t;
    typedef Timestamp_t Timestamp;

    typedef octet VendorId_vendorId_t[2];

    /* Type used to represent the vendor of the service implementing the RTPS protocol. */
    struct VendorId_t {
      VendorId_vendorId_t vendorId;
    };
    typedef VendorId_t VendorId;

    /* Type used to hold sequence numbers. */
    struct SequenceNumber_t {
      long high;
      unsigned long low;
    };
    typedef SequenceNumber_t SequenceNumber;

    /* SequenceNumberSet SubmessageElements are used as parts of several messages to
       provide binary information about individual sequence numbers within a range. */
    /* TBD: requires custom de/serializer */
    struct SequenceNumberSet {
      SequenceNumber_t bitmapBase;
      sequence<long, 8> bitmap;
    };

    /* Type used to hold fragment numbers. */
    struct FragmentNumber_t {
      unsigned long value;
    };
    typedef FragmentNumber_t FragmentNumber;

    /* FragmentNumberSet SubmessageElements are used to provide binary information
       about individual fragment numbers within a range. */
    /* TBD: requires custom de/serializer */
    struct FragmentNumberSet {
      FragmentNumber_t bitmapBase;
      sequence<long, 8> bitmap;
    };

    typedef octet Locator_address_t[16];

    /* Type used to represent the addressing information needed to send a message
       to an RTPS Endpoint */
    struct Locator_t {
      long kind;
      unsigned long port;
      Locator_address_t address;
    };

    /* LocatorList is used to specify a list of locators. */
    typedef sequence<Locator_t, 8> LocatorList;

    /* Specialization of Locator_t used to hold UDP IPv4 locators using a more
       compact representation. */
    struct LocatorUDPv4_t {
      unsigned long address;
      unsigned long port;
    };
    typedef LocatorUDPv4_t LocatorUDPv4;

    /* Enumeration used to distinguish whether a Topic has defined some fields
       within to be used as the ‘key’ that identifies data-instances within the
       Topic. */
    struct TopicKind_t {
      long value;
    };

    /* Enumeration used to indicate the level of the reliability used for
       communications. */
    struct ReliabilityKind_t {
      long value;
    };

    /* Type used to encapsulate a count that is incremented monotonically, used
       to identify message duplicates. */
    struct Count_t {
      long value;
    };
    typedef Count_t Count;

    /* Identifies the version of the RTPS protocol. */
    struct ProtocolVersion_t {
      octet major;
      octet minor;
    };
    typedef ProtocolVersion_t ProtocolVersion;

    typedef octet KeyHash_value_t[16];
    struct KeyHash_t {
      KeyHash_value_t value;
    };

    typedef octet StatusInfo_value_t[4];
    struct StatusInfo_t {
      StatusInfo_value_t value;
    };

    /* Type used to uniquely identify a parameter in a parameter list. */
    struct ParameterId_t {
      short value;
    };

    /* information to enable content filtering */
    struct ContentFilterProperty_t {
      string<256> contentFilteredTopicName;
      string<256> relatedTopicName;
      string<256> filterClassName;
      string filterExpression;
      sequence<string> expressionParameters;
    };

    /* For each filter signature, the results indicate whether the
       sample passed the filter. */
    typedef sequence<long> FilterResult_t;

    /* A list of filters that were applied to the sample. */
    typedef long FilterSignature_t[4];


    struct ContentFilterInfo_t {
      FilterResult_t filterResult;
      sequence<FilterSignature_t> filterSignatures;
    };

    struct Property_t {
      string name;
      string value;
    };

    struct EntityName_t {
      string name;
    };

    /* requires custom de/marshalling */
    struct Parameter {
      ParameterId_t parameterId;
      sequence<octet> value;
    };

    /* contains a list of Parameters, terminated with a sentinel */
    typedef sequence<Parameter> ParameterList;

    struct OriginalWriterInfo_t {
      GUID_t originalWriterGUID;
      SequenceNumber_t originalWriterSN;
      ParameterList originalWriterQos;
    };

    typedef unsigned long BuiltinEndpointSet_t;

    /* TBD: Not sure how best to represent SerializedPayload */
    typedef sequence<octet> SerializedPayload_t;
    typedef SerializedPayload_t SerializedPayload;

    const long LOCATOR_KIND_INVALID = -1;
    const unsigned long LOCATOR_PORT_INVALID = 0;
    const long LOCATOR_KIND_RESERVED = 0;
    const long LOCATOR_KIND_UDPv4 = 1;
    const long LOCATOR_KIND_UDPv6  = 2;

    const short NO_KEY = 1;
    const short WITH_KEY = 2;

    const short BEST_EFFORT = 1;
    const short RELIABLE = 3;

    const BuiltinEndpointSet_t DISC_BUILTIN_ENDPOINT_PARTICIPANT_ANNOUNCER = 0x00000001 << 0;
    const BuiltinEndpointSet_t DISC_BUILTIN_ENDPOINT_PARTICIPANT_DETECTOR = 0x00000001 << 1;
    const BuiltinEndpointSet_t DISC_BUILTIN_ENDPOINT_PUBLICATION_ANNOUNCER = 0x00000001 << 2;
    const BuiltinEndpointSet_t DISC_BUILTIN_ENDPOINT_PUBLICATION_DETECTOR = 0x00000001 << 3;
    const BuiltinEndpointSet_t DISC_BUILTIN_ENDPOINT_SUBSCRIPTION_ANNOUNCER = 0x00000001 << 4;
    const BuiltinEndpointSet_t DISC_BUILTIN_ENDPOINT_SUBSCRIPTION_DETECTOR = 0x00000001 << 5;
    const BuiltinEndpointSet_t DISC_BUILTIN_ENDPOINT_PARTICIPANT_PROXY_ANNOUNCER = 0x00000001 << 6;
    const BuiltinEndpointSet_t DISC_BUILTIN_ENDPOINT_PARTICIPANT_PROXY_DETECTOR = 0x00000001 << 7;
    const BuiltinEndpointSet_t DISC_BUILTIN_ENDPOINT_PARTICIPANT_STATE_ANNOUNCER = 0x00000001 << 8;
    const BuiltinEndpointSet_t DISC_BUILTIN_ENDPOINT_PARTICIPANT_STATE_DETECTOR = 0x00000001 << 9;
    const BuiltinEndpointSet_t BUILTIN_ENDPOINT_PARTICIPANT_MESSAGE_DATA_WRITER = 0x00000001 << 10;
    const BuiltinEndpointSet_t BUILTIN_ENDPOINT_PARTICIPANT_MESSAGE_DATA_READER = 0x00000001 << 11;

  };
};

#endif /* _RTPS_RTPSBASEMESSAGETYPES_IDL_ */
