/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

#ifdef OPENDDS_SECURITY
#ifndef OPENDDS_DCPS_RTPS_RTPS_SECURITY_IDL
#define OPENDDS_DCPS_RTPS_RTPS_SECURITY_IDL

#include <dds/DCPS/RTPS/RtpsCore.idl>
#include <dds/DdsSecurityCore.idl>

module OpenDDS {
  module Security {

    enum DiscoveredParticipantDataKind {
      DPDK_NONE,
      DPDK_ORIGINAL,
      DPDK_ENHANCED,
      DPDK_SECURE
    };

    // top-level data type for SPDP
    struct SPDPdiscoveredParticipantData {
      DiscoveredParticipantDataKind dataKind;
      DDS::Security::ParticipantBuiltinTopicDataSecure ddsParticipantDataSecure;
      OpenDDS::RTPS::ParticipantProxy_t participantProxy;
      OpenDDS::RTPS::Duration_t leaseDuration;
      DCPS::MonotonicTime_t discoveredAt;
    };
  };
};

#endif
#endif
