module Messenger {

#pragma DCPS_DATA_TYPE "Messenger::Message"
#pragma DCPS_DATA_KEY "Messenger::Message count"

  typedef string<255> BoundedString;

  struct Message {
    BoundedString text;
    long count;
  };

};
