name: "omg-dds/dds-rtps"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  Linux:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout OpenDDS
      uses: actions/checkout@v7
      with:
        path: OpenDDS
        submodules: true
    - name: checkout dds-rtps
      uses: actions/checkout@v7
      with:
        repository: omg-dds/dds-rtps
        path: dds-rtps
    - name: checkout ACE_TAO
      uses: actions/checkout@v7
      with:
        repository: DOCGroup/ACE_TAO
        ref: Latest_Micro
        path: OpenDDS/ACE_TAO
    - name: get ACE_TAO commit
      shell: bash
      run: |
        cd OpenDDS/ACE_TAO
        export ACE_COMMIT=$(git rev-parse HEAD)
        echo "ACE_COMMIT=$ACE_COMMIT" >> $GITHUB_ENV
    - name: get compiler version
      shell: bash
      run: |
        export COMPILER_VERSION=$(g++ --version 2>&1 | head -n 1)
        echo "COMPILER_VERSION=$COMPILER_VERSION" >> $GITHUB_ENV
    - name: checkout MPC
      uses: actions/checkout@v7
      with:
        repository: DOCGroup/MPC
        path: OpenDDS/ACE_TAO/ACE/MPC
    - name: configure OpenDDS
      run: |
        cd OpenDDS
        ./configure --optimize --no-debug --static --no-inline
        tools/scripts/show_build_config.pl
    - uses: ammaraskar/gcc-problem-matcher@0.3.0
    - name: build OpenDDS
      shell: bash
      run: |
        cd OpenDDS
        make -j4 OpenDDS_Rtps_Udp
    - name: build shape_main
      shell: bash
      run: |
        . OpenDDS/setenv.sh
        cd dds-rtps/srcCxx/opendds-cmake
        cmake -S . -B build
        cmake --build build -- -j4
    - name: rename shape_main artifact
      shell: bash
      run: |
        OPENDDS_VERSION=$(sed -n 's/^#define OPENDDS_VERSION "\(.*\)"/\1/p' OpenDDS/dds/Version.h)
        echo "OPENDDS_VERSION=$OPENDDS_VERSION" >> $GITHUB_ENV
        cp dds-rtps/srcCxx/opendds-cmake/build/shape_main \
          dds-rtps/srcCxx/opendds-cmake/build/opendds-${OPENDDS_VERSION}_shape_main_linux
    - name: upload shape_main artifact
      uses: actions/upload-artifact@v7
      with:
        name: opendds-${{ env.OPENDDS_VERSION }}_shape_main_linux
        path: dds-rtps/srcCxx/opendds-cmake/build/opendds-${{ env.OPENDDS_VERSION }}_shape_main_linux
