
module Xyz {

#pragma DCPS_DATA_TYPE "Xyz::SampleType"
#pragma DCPS_DATA_KEY "Xyz::SampleType a_long_value"

  // Example user defined "SampleType" structure
  struct SampleType {
    long  a_long_value;  // the instance key
    long  handle_value;
    long  sample_sequence;
    long  writer_id;
  };

};
