/*
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

module Messenger {

    struct DataField {
        string name;
        sequence<octet> value;
    };

    typedef sequence<DataField> DataSeq;


  @topic
  struct Message {
    DataSeq data;
    string text;
    @key
    long   subject_id;
    long   count;
  };
};
