/*
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

module Messenger {

  @topic
  struct Message {
    string text;
    @key
    long   subject_id;
    long   count;
  };
};
